func TestSQLHorizontalSplitting(t *testing.T) {
	var primaryKeyList map[string][]string
	dataString := `{"schema":{"type":"struct","fields":[{"type":"struct","fields":[{"type":"int32","optional":false,"default":0,"field":"id"},{"type":"string","optional":true,"field":"message"},{"type":"int64","optional":false,"name":"io.debezium.time.MicroTimestamp","version":1,"default":0,"field":"created_at"}],"optional":true,"name":"test2.public.t.Value","field":"before"},{"type":"struct","fields":[{"type":"int32","optional":false,"default":0,"field":"id"},{"type":"string","optional":true,"field":"message"},{"type":"int64","optional":false,"name":"io.debezium.time.MicroTimestamp","version":1,"default":0,"field":"created_at"}],"optional":true,"name":"test2.public.t.Value","field":"after"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"version"},{"type":"string","optional":false,"field":"connector"},{"type":"string","optional":false,"field":"name"},{"type":"int64","optional":false,"field":"ts_ms"},{"type":"string","optional":true,"name":"io.debezium.data.Enum","version":1,"parameters":{"allowed":"true,last,false,incremental"},"default":"false","field":"snapshot"},{"type":"string","optional":false,"field":"db"},{"type":"string","optional":true,"field":"sequence"},{"type":"string","optional":false,"field":"schema"},{"type":"string","optional":false,"field":"table"},{"type":"int64","optional":true,"field":"txId"},{"type":"int64","optional":true,"field":"lsn"},{"type":"int64","optional":true,"field":"xmin"}],"optional":false,"name":"io.debezium.connector.postgresql.Source","field":"source"},{"type":"string","optional":false,"field":"op"},{"type":"int64","optional":true,"field":"ts_ms"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"id"},{"type":"int64","optional":false,"field":"total_order"},{"type":"int64","optional":false,"field":"data_collection_order"}],"optional":true,"name":"event.block","version":1,"field":"transaction"}],"optional":false,"name":"test2.public.t.Envelope","version":1},"payload":{"before":null,"after":{"id":270077,"message":"test","created_at":1675844381816962},"source":{"version":"2.1.2.Final","connector":"postgresql","name":"test2","ts_ms":1675844381825,"snapshot":"false","db":"ta1","sequence":"[\"497534528\",\"497534920\"]","schema":"public","table":"table","txId":775139,"lsn":497534920,"xmin":null},"op":"c","ts_ms":1675844382293,"transaction":null}}`
	var dat model.AutoGenerated
	err := json.Unmarshal([]byte(dataString), &dat)
	if err != nil {
		fmt.Println(err)
		t.Errorf("Error unmarshal data")
	}
	sql, err := ConvertDataToSQLTest(primaryKeyList, dat, true)

	if err != nil {
		t.Errorf(err.Error())
		t.Errorf("Error convert data to sql")
	}
	expected := "INSERT INTO public.table (created_at,text,id) VALUES ('2023-02-08T08:19:41.816962Z','test',270077);"
	fmt.Println(sql)
	fmt.Println(expected)
	if SortStringByCharacter(sql) != SortStringByCharacter(expected) {

		t.Errorf("Error rename column on Insert")
	}
	dataString = `{"schema":{"type":"struct","fields":[{"type":"struct","fields":[{"type":"int32","optional":false,"default":0,"field":"id"},{"type":"string","optional":true,"field":"message"},{"type":"int64","optional":false,"name":"io.debezium.time.MicroTimestamp","version":1,"default":0,"field":"created_at"}],"optional":true,"name":"test2.public.t.Value","field":"before"},{"type":"struct","fields":[{"type":"int32","optional":false,"default":0,"field":"id"},{"type":"string","optional":true,"field":"message"},{"type":"int64","optional":false,"name":"io.debezium.time.MicroTimestamp","version":1,"default":0,"field":"created_at"}],"optional":true,"name":"test2.public.t.Value","field":"after"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"version"},{"type":"string","optional":false,"field":"connector"},{"type":"string","optional":false,"field":"name"},{"type":"int64","optional":false,"field":"ts_ms"},{"type":"string","optional":true,"name":"io.debezium.data.Enum","version":1,"parameters":{"allowed":"true,last,false,incremental"},"default":"false","field":"snapshot"},{"type":"string","optional":false,"field":"db"},{"type":"string","optional":true,"field":"sequence"},{"type":"string","optional":false,"field":"schema"},{"type":"string","optional":false,"field":"table"},{"type":"int64","optional":true,"field":"txId"},{"type":"int64","optional":true,"field":"lsn"},{"type":"int64","optional":true,"field":"xmin"}],"optional":false,"name":"io.debezium.connector.postgresql.Source","field":"source"},{"type":"string","optional":false,"field":"op"},{"type":"int64","optional":true,"field":"ts_ms"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"id"},{"type":"int64","optional":false,"field":"total_order"},{"type":"int64","optional":false,"field":"data_collection_order"}],"optional":true,"name":"event.block","version":1,"field":"transaction"}],"optional":false,"name":"test2.public.t.Envelope","version":1},"payload":{"before":{"id":270077,"message":"test","created_at":1675844381816962},"after":null,"source":{"version":"2.1.2.Final","connector":"postgresql","name":"test2","ts_ms":1675844381825,"snapshot":"false","db":"ta1","sequence":"[\"497534528\",\"497534920\"]","schema":"public","table":"table","txId":775139,"lsn":497534920,"xmin":null},"op":"d","ts_ms":1675844382293,"transaction":null}}`
	err = json.Unmarshal([]byte(dataString), &dat)
	if err != nil {
		fmt.Println(err)
		t.Errorf("Error unmarshal data")
	}
	sql, err = ConvertDataToSQLTest(primaryKeyList, dat, true)

	if err != nil {
		t.Errorf(err.Error())
		t.Errorf("Error convert data to sql")
	}

	expected = "DELETE FROM public.table WHERE id=270077 AND created_at='2023-02-08T08:19:41.816962Z' AND text='test';"
	fmt.Println(sql)
	fmt.Println(expected)
	if SortStringByCharacter(sql) != SortStringByCharacter(expected) {

		t.Errorf("Error rename column on Delete")
	}
}