ALTER TABLE public.rename_column RENAME message to text;
DROP TABLE public.t;
ALTER TABLE public.add_column ADD COLUMN add_column int;
ALTER TABLE public.add_column ADD COLUMN add_column_non_null int NOT NULL DEFAULT 'nonNull';
ALTER TABLE public.drop_column DROP COLUMN message;
ALTER TABLE public.drop_column_non_null DROP COLUMN message;
ALTER TABLE public.rename_table RENAME TO rename_table_new;
ALTER TABLE public.test_temporal RENAME time_mili TO time2;
ALTER TABLE public.test_temporal ALTER COLUMN time2 TYPE time (3);
ALTER TABLE public.test_temporal RENAME timestamp_mili TO timestamp2;
ALTER TABLE public.test_temporal ALTER COLUMN timestamp2 TYPE timestamp (3);
ALTER TABLE public.test_temporal RENAME timestamp TO timestamp_with_time_zone2;
ALTER TABLE public.test_temporal ALTER COLUMN timestamp_with_time_zone2 TYPE timestamptz;
CREATE TABLE  public.create_table (id Serial Primary Key ,message text ,created_at timestamp);
CREATE TABLE  public.create_table_after_2022 (id Serial Primary Key ,message text ,created_at timestamp);
