package utils

import (
	"github.com/rweebs/cdc-bowo/internal/app/config"
	"github.com/rweebs/cdc-bowo/internal/app/model"
)

func AddColumn(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
	// if data.Payload.After != nil {
	// 	tableMap := data.Payload.After.(map[string]interface{})
	// 	for _, v := range config.AddColumn {
	// 		if v.IsNullable {
	// 			tableMap[v.Column] = nil
	// 		} else {
	// 			tableMap[v.Column] = v.Default
	// 		}
	// 	}

	// 	data.Payload.After = tableMap
	// }
	// if data.Payload.Before != nil {
	// 	tableMapBefore := data.Payload.Before.(map[string]interface{})
	// 	for _, v := range config.AddColumn {
	// 		if v.IsNullable {
	// 			tableMapBefore[v.Column] = nil
	// 		} else {
	// 			tableMapBefore[v.Column] = v.Default
	// 		}
	// 	}
	// 	data.Payload.Before = tableMapBefore
	// }
	return data
}

func AddColumnDest(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
	if data.Payload.After != nil {
		tableMapAfter := data.Payload.After.(map[string]interface{})
		for _, v := range config.AddColumn {
			delete(tableMapAfter, v.Column)
		}
		data.Payload.After = tableMapAfter
	}
	if data.Payload.Before != nil {
		tableMapBefore := data.Payload.Before.(map[string]interface{})
		for _, v := range config.AddColumn {
			delete(tableMapBefore, v.Column)
		}
		data.Payload.Before = tableMapBefore
	}
	return data
}

func DropColumn(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
	if data.Payload.After != nil {
		tableMap := data.Payload.After.(map[string]interface{})
		for _, v := range config.DropColumn {
			delete(tableMap, v.Column)
		}
		data.Payload.After = tableMap
	}
	if data.Payload.Before != nil {
		tableMapBefore := data.Payload.Before.(map[string]interface{})
		for _, v := range config.DropColumn {
			delete(tableMapBefore, v.Column)
		}
		data.Payload.Before = tableMapBefore
	}
	return data
}

func DropColumnDest(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
	if data.Payload.After != nil {
		tableMap := data.Payload.After.(map[string]interface{})
		for _, v := range config.DropColumn {
			if v.IsNullable {
				tableMap[v.Column] = nil
			} else {
				tableMap[v.Column] = v.Default
			}
		}

		data.Payload.After = tableMap
	}
	if data.Payload.Before != nil {
		tableMapBefore := data.Payload.Before.(map[string]interface{})
		for _, v := range config.DropColumn {
			if v.IsNullable {
				tableMapBefore[v.Column] = nil
			} else {
				tableMapBefore[v.Column] = v.Default
			}
		}
		data.Payload.Before = tableMapBefore
	}
	return data
}
func CreateTableDest(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
	data.Payload.Op = "s"
	return data
}

func DropTable(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
	data.Payload.Op = "s"
	return data
}

func RenameTable(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
	for _, v := range config.RenameTable {
		data.Payload.Source.Table = v.NewName
	}
	return data
}

func RenameTableDest(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
	for _, v := range config.RenameTable {
		data.Payload.Source.Table = v.OldName
	}
	return data
}
func RenameColumn(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
	if data.Payload.After != nil {
		tableMap := data.Payload.After.(map[string]interface{})
		dats := data.Schema.Fields[1].Fields
		for _, v := range config.RenameColumn {
			tableMap[v.NewName] = tableMap[v.OldName]
			delete(tableMap, v.OldName)
			for i := range dats {
				if dats[i].Field == v.OldName {
					dats[i].Field = v.NewName
				}
			}
		}
		data.Payload.After = tableMap
		data.Schema.Fields[1].Fields = dats
	}
	if data.Payload.Before != nil {
		tableMapBefore := data.Payload.Before.(map[string]interface{})
		dats := data.Schema.Fields[1].Fields
		for _, v := range config.RenameColumn {
			tableMapBefore[v.NewName] = tableMapBefore[v.OldName]
			delete(tableMapBefore, v.OldName)
			for i := range dats {
				if dats[i].Field == v.OldName {
					dats[i].Field = v.NewName
				}
			}
		}
		data.Payload.Before = tableMapBefore
		data.Schema.Fields[1].Fields = dats
	}
	return data
}

func RenameColumnDest(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
	if data.Payload.After != nil {
		tableMap := data.Payload.After.(map[string]interface{})
		dats := data.Schema.Fields[1].Fields
		for _, v := range config.RenameColumn {
			tableMap[v.OldName] = tableMap[v.NewName]
			delete(tableMap, v.NewName)
			for i := range dats {
				if dats[i].Field == v.NewName {
					dats[i].Field = v.OldName
				}
			}

		}

		data.Payload.After = tableMap
		data.Schema.Fields[1].Fields = dats
	}
	if data.Payload.Before != nil {
		tableMapBefore := data.Payload.Before.(map[string]interface{})
		dats := data.Schema.Fields[1].Fields
		for _, v := range config.RenameColumn {
			tableMapBefore[v.OldName] = tableMapBefore[v.NewName]
			delete(tableMapBefore, v.NewName)
			for i := range dats {
				if dats[i].Field == v.NewName {
					dats[i].Field = v.OldName
				}
			}
		}
		data.Payload.Before = tableMapBefore
		data.Schema.Fields[1].Fields = dats
	}
	return data
}

//	func HorizontalSplitting(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
//		if data.Payload.After != nil {
//			tableMap := data.Payload.After.(map[string]interface{})
//			dats := data.Schema.Fields[1].Fields
//			for _, v := range config.RenameColumn {
//				tableMap[v.NewName] = tableMap[v.OldName]
//				delete(tableMap, v.OldName)
//				for i := range dats {
//					if dats[i].Field == v.OldName {
//						dats[i].Field = v.NewName
//					}
//				}
//			}
//			data.Payload.After = tableMap
//			data.Schema.Fields[1].Fields = dats
//		}
//		if data.Payload.Before != nil {
//			tableMapBefore := data.Payload.Before.(map[string]interface{})
//			dats := data.Schema.Fields[1].Fields
//			for _, v := range config.RenameColumn {
//				tableMapBefore[v.NewName] = tableMapBefore[v.OldName]
//				delete(tableMapBefore, v.OldName)
//				for i := range dats {
//					if dats[i].Field == v.OldName {
//						dats[i].Field = v.NewName
//					}
//				}
//			}
//			data.Payload.Before = tableMapBefore
//			data.Schema.Fields[1].Fields = dats
//		}
//		return data
//	}
func ConvertSchema(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
	if len(config.DropTable) > 0 {
		data = DropTable(data, config)
		return data
	}
	if len(config.RenameTable) > 0 {
		data = RenameTable(data, config)
	}
	if len(config.RenameColumn) > 0 {
		data = RenameColumn(data, config)
	}
	if len(config.DropColumn) > 0 {
		data = DropColumn(data, config)
	}
	if len(config.AddColumn) > 0 {
		data = AddColumn(data, config)
	}
	// if len(config.HorizontalSplitting) > 0 {
	// 	data = HorizontalSplitting(data, config)
	// }
	// data2, _ := json.MarshalIndent(data, "", "  ")
	// fmt.Println(string(data2))
	return data
}

func ConvertSchemaDest(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
	if len(config.CreateTable) > 0 {
		data = CreateTableDest(data, config)
		return data
	}
	if len(config.RenameTable) > 0 {
		data = RenameTableDest(data, config)
	}
	if len(config.RenameColumn) > 0 {
		data = RenameColumnDest(data, config)
	}
	if len(config.DropColumn) > 0 {
		data = DropColumnDest(data, config)
	}
	if len(config.AddColumn) > 0 {
		data = AddColumnDest(data, config)
	}
	return data
}
