package utils

import (
	"github.com/rweebs/cdc-bowo/internal/app/config"
	"github.com/rweebs/cdc-bowo/internal/app/model"
)

func DropColumn(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
	tableMap := data.Payload.After.(map[string]interface{})
	for _, v := range config.DropColumn {
		delete(tableMap, v.Column)
	}
	data.Payload.After = tableMap
	return data
}

func DropColumn2(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
	tableMap := data.Payload.After.(map[string]interface{})
	for _, v := range config.DropColumn {
		if v.IsNullable {
			tableMap[v.Column] = nil
		} else {
			tableMap[v.Column] = v.Default
		}
	}

	data.Payload.After = tableMap
	return data
}

func RenameTable(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
	for _, v := range config.RenameTable {
		data.Payload.Source.Table = v.NewName
	}
	return data
}

func RenameColumn(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
	tableMap := data.Payload.After.(map[string]interface{})
	for _, v := range config.RenameColumn {
		tableMap[v.NewName] = tableMap[v.OldName]
		delete(tableMap, v.OldName)
	}

	data.Payload.After = tableMap
	return data
}

func ModifyDataType(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
	tableMap := data.Payload.After.(map[string]interface{})
	for _, v := range config.RenameColumn {
		tableMap[v.NewName] = tableMap[v.OldName]
		delete(tableMap, v.OldName)
	}

	data.Payload.After = tableMap
	return data
}

func ConvertSchema(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
	if len(config.RenameTable) > 0 {
		data = RenameTable(data, config)
	}
	if len(config.RenameColumn) > 0 {
		data = RenameColumn(data, config)
	}
	if len(config.DropColumn) > 0 {
		data = DropColumn(data, config)
	}
	return data
}
