package utils

import (
	"encoding/json"
	"fmt"
	"testing"

	"github.com/rweebs/cdc-bowo/internal/app/config"
	"github.com/rweebs/cdc-bowo/internal/app/model"
)

func TestDropColumn(t *testing.T) {
	dataString := `{"schema":{"type":"struct","fields":[{"type":"struct","fields":[{"type":"int32","optional":false,"default":0,"field":"id"},{"type":"string","optional":true,"field":"message"},{"type":"int64","optional":false,"name":"io.debezium.time.MicroTimestamp","version":1,"default":0,"field":"created_at"}],"optional":true,"name":"test2.public.t.Value","field":"before"},{"type":"struct","fields":[{"type":"int32","optional":false,"default":0,"field":"id"},{"type":"string","optional":true,"field":"message"},{"type":"int64","optional":false,"name":"io.debezium.time.MicroTimestamp","version":1,"default":0,"field":"created_at"}],"optional":true,"name":"test2.public.t.Value","field":"after"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"version"},{"type":"string","optional":false,"field":"connector"},{"type":"string","optional":false,"field":"name"},{"type":"int64","optional":false,"field":"ts_ms"},{"type":"string","optional":true,"name":"io.debezium.data.Enum","version":1,"parameters":{"allowed":"true,last,false,incremental"},"default":"false","field":"snapshot"},{"type":"string","optional":false,"field":"db"},{"type":"string","optional":true,"field":"sequence"},{"type":"string","optional":false,"field":"schema"},{"type":"string","optional":false,"field":"table"},{"type":"int64","optional":true,"field":"txId"},{"type":"int64","optional":true,"field":"lsn"},{"type":"int64","optional":true,"field":"xmin"}],"optional":false,"name":"io.debezium.connector.postgresql.Source","field":"source"},{"type":"string","optional":false,"field":"op"},{"type":"int64","optional":true,"field":"ts_ms"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"id"},{"type":"int64","optional":false,"field":"total_order"},{"type":"int64","optional":false,"field":"data_collection_order"}],"optional":true,"name":"event.block","version":1,"field":"transaction"}],"optional":false,"name":"test2.public.t.Envelope","version":1},"payload":{"before":null,"after":{"id":270077,"message":"test","created_at":1675844381816962},"source":{"version":"2.1.2.Final","connector":"postgresql","name":"test2","ts_ms":1675844381825,"snapshot":"false","db":"ta1","sequence":"[\"497534528\",\"497534920\"]","schema":"public","table":"t","txId":775139,"lsn":497534920,"xmin":null},"op":"c","ts_ms":1675844382293,"transaction":null}}`
	var data model.AutoGenerated
	err := json.Unmarshal([]byte(dataString), &data)
	if err != nil {
		t.Errorf("Error unmarshal data")
	}
	config := config.DDLTransform{
		DropColumn: []struct {
			Schema     string      `mapstructure:"schema"`
			Table      string      `mapstructure:"table"`
			Column     string      `mapstructure:"column"`
			IsNullable bool        `mapstructure:"isNullable"`
			Default    interface{} `mapstructure:"default"`
		}{{
			Column: "column1",
		},
		},
	}

	data = DropColumn(data, config)
	fmt.Println(data.Payload.After.(map[string]interface{}))
	if len(data.Payload.After.(map[string]interface{})) == 0 {
		t.Errorf("Expected 1 column, got %d", len(data.Payload.After.(map[string]interface{})))
	}

}

func TestRenameColumn(t *testing.T) {
	dataString := `{"schema":{"type":"struct","fields":[{"type":"struct","fields":[{"type":"int32","optional":false,"default":0,"field":"id"},{"type":"string","optional":true,"field":"message"},{"type":"int64","optional":false,"name":"io.debezium.time.MicroTimestamp","version":1,"default":0,"field":"created_at"}],"optional":true,"name":"test2.public.t.Value","field":"before"},{"type":"struct","fields":[{"type":"int32","optional":false,"default":0,"field":"id"},{"type":"string","optional":true,"field":"message"},{"type":"int64","optional":false,"name":"io.debezium.time.MicroTimestamp","version":1,"default":0,"field":"created_at"}],"optional":true,"name":"test2.public.t.Value","field":"after"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"version"},{"type":"string","optional":false,"field":"connector"},{"type":"string","optional":false,"field":"name"},{"type":"int64","optional":false,"field":"ts_ms"},{"type":"string","optional":true,"name":"io.debezium.data.Enum","version":1,"parameters":{"allowed":"true,last,false,incremental"},"default":"false","field":"snapshot"},{"type":"string","optional":false,"field":"db"},{"type":"string","optional":true,"field":"sequence"},{"type":"string","optional":false,"field":"schema"},{"type":"string","optional":false,"field":"table"},{"type":"int64","optional":true,"field":"txId"},{"type":"int64","optional":true,"field":"lsn"},{"type":"int64","optional":true,"field":"xmin"}],"optional":false,"name":"io.debezium.connector.postgresql.Source","field":"source"},{"type":"string","optional":false,"field":"op"},{"type":"int64","optional":true,"field":"ts_ms"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"id"},{"type":"int64","optional":false,"field":"total_order"},{"type":"int64","optional":false,"field":"data_collection_order"}],"optional":true,"name":"event.block","version":1,"field":"transaction"}],"optional":false,"name":"test2.public.t.Envelope","version":1},"payload":{"before":null,"after":{"id":270077,"message":"test","created_at":1675844381816962},"source":{"version":"2.1.2.Final","connector":"postgresql","name":"test2","ts_ms":1675844381825,"snapshot":"false","db":"ta1","sequence":"[\"497534528\",\"497534920\"]","schema":"public","table":"t","txId":775139,"lsn":497534920,"xmin":null},"op":"c","ts_ms":1675844382293,"transaction":null}}`
	var data model.AutoGenerated
	err := json.Unmarshal([]byte(dataString), &data)
	if err != nil {
		t.Errorf("Error unmarshal data")
	}
	config := config.DDLTransform{
		RenameColumn: []struct {
			Schema  string "mapstructure:\"schema\""
			Table   string "mapstructure:\"table\""
			OldName string "mapstructure:\"oldName\""
			NewName string "mapstructure:\"newName\""
		}{{
			OldName: "column1",
			NewName: "column2",
		},
		},
	}

	data = DropColumn(data, config)
	if data.Payload.After.(map[string]interface{})["column2"] == "value1" {
		t.Errorf("Error rename column")
	}

}
