package utils

import (
	"database/sql"
	"fmt"
	"log"
	"reflect"
	"strings"
	"time"

	"github.com/rweebs/cdc-bowo/internal/app/config"
	"github.com/rweebs/cdc-bowo/internal/app/model"
)

type Column []string
type ColumnValue []string

func DetectTemporalType(data model.AutoGenerated, key string) (bool, string) {
	// debeziumTimeMap := map[string]bool{"io.debe"}
	var temporalType bool
	var temporalTypeString string

	for _, data := range data.Schema.Fields[1].Fields {
		if data.Field == key {
			return data.Name == "io.debezium.time.MicroTimestamp" || data.Name == "io.debezium.time.Timestamp" || data.Name == "io.debezium.time.Date" || data.Name == "io.debezium.time.MicroTime" || data.Name == "io.debezium.time.Time", data.Name
		}
	}
	return temporalType, temporalTypeString
}
func ConvertTemporalOnInsert(key string, value interface{}) string {
	var result string
	if key == "io.debezium.time.MicroTimestamp" {
		fmt.Println(key, value)
		result = fmt.Sprintf("'%s'", time.Unix(0, int64(value.(float64))*1000).UTC().Format(time.RFC3339Nano))
	}
	if key == "io.debezium.time.Timestamp" {
		fmt.Println(key, value)
		result = fmt.Sprintf("'%s'", time.Unix(0, int64(value.(float64))*1000000).UTC().Format(time.RFC3339Nano))
	}
	if key == "io.debezium.time.Date" {
		date := time.Unix(int64(value.(float64))*86400, 0).UTC().Format("2006-01-02")
		result = fmt.Sprintf("'%s'", date)
	}
	if key == "io.debezium.time.MicroTime" {

		result = fmt.Sprintf("'%s'", time.Unix(0, int64(value.(float64))*1000).UTC().Format("15:04:05.000000"))
	}
	if key == "io.debezium.time.Time" {
		result = fmt.Sprintf("'%s'", time.Unix(0, int64(value.(float64))*1000000).UTC().Format("15:04:05.000000"))
	}

	return result
}
func ConvertTemporalOnDelete(key string, column string, value interface{}) string {
	var result string
	if key == "io.debezium.time.MicroTimestamp" {
		result = fmt.Sprintf("%s='%s'", column, time.Unix(0, int64(value.(float64))*1000).UTC().Format(time.RFC3339Nano))
	}
	if key == "io.debezium.time.Timestamp" {
		result = fmt.Sprintf("%s='%s'", column, time.Unix(0, int64(value.(float64))*1000000).UTC().Format(time.RFC3339Nano))
	}
	if key == "io.debezium.time.Date" {
		date := time.Unix(int64(value.(float64))*86400, 0).UTC().Format("2006-01-02")
		result = fmt.Sprintf("%s='%s'", column, date)
	}
	if key == "io.debezium.time.MicroTime" {
		result = fmt.Sprintf("%s='%s'", column, time.Unix(0, int64(value.(float64))*1000).UTC().Format("15:04:05.000000"))
	}
	if key == "io.debezium.time.Time" {
		result = fmt.Sprintf("%s='%s'", column, time.Unix(0, int64(value.(float64))*1000000).UTC().Format("15:04:05.000000"))
	}
	return result
}
func ConvertDataToSQLNormal(data model.AutoGenerated, primaryKey map[string][]string, configs config.DDLTransform, isFromSource bool, db *sql.DB) string {
	var Query string
	schema := data.Payload.Source.Schema
	table := data.Payload.Source.Table
	columns := primaryKey[fmt.Sprintf("%s.%s", schema, table)]
	var horizontalSplit = func() {
		var partQuery string
		var column string
		var columnValue string
		var value map[string]interface{}
		if data.Payload.Op == "c" {
			value = data.Payload.After.(map[string]interface{})
		} else {
			value = data.Payload.Before.(map[string]interface{})
		}
		for key, val := range value {
			column = key
			if val == nil {
				columnValue = "NULL"
			} else {
				if reflect.ValueOf(val).Kind() == reflect.String {
					columnValue = fmt.Sprintf("'%v'", val)
				} else if ok, temporalType := DetectTemporalType(data, key); ok {
					columnValue = ConvertTemporalOnInsert(temporalType, val)
				} else {
					columnValue = fmt.Sprintf("%v", val)
				}

			}
			partQuery += fmt.Sprintf(" %s as %s,", columnValue, column)

		}
		partQuery = strings.TrimSuffix(partQuery, ",")
		select_query := fmt.Sprintf("SELECT COUNT(*) FROM (SELECT %s) as test where %s;", partQuery, configs.HorizontalSplitting[0].Criteria)
		fmt.Println(select_query)
		var count int
		err := db.QueryRow(select_query).Scan(&count)
		if err != nil {
			log.Fatal(err)
		}
		fmt.Println(count)
		if count > 0 {
			table = configs.HorizontalSplitting[0].DestTable
		}
	}
	var delete = func() {
		dataType := map[string]string{}
		if isFromSource {
			for _, v := range configs.ModifyDataType {
				dataType[v.Column] = v.NewType
			}
		} else {
			for _, v := range configs.ModifyDataType {
				dataType[v.Column] = v.OldType
			}
		}
		var primary string
		tableMap := map[string]interface{}{}
		var value reflect.Value
		if data.Payload.Op == "d" || len(columns) == 0 {
			value = reflect.ValueOf(data.Payload.Before)
		} else {
			value = reflect.ValueOf(data.Payload.After)
		}

		if value.Kind() == reflect.Map {
			keys := value.MapKeys()
			for _, key := range keys {

				tableMap[key.String()] = value.MapIndex(key)
			}
		}
		if len(columns) == 0 {
			keys := value.MapKeys()
			for i, column := range keys {
				v := value.MapIndex(column)
				if i != 0 {
					primary += " AND "
				}
				if reflect.ValueOf(v.Interface()).Kind() == reflect.String {
					primary += fmt.Sprintf("%s='%v'", column.String(), v.Interface())
				} else if v.Interface() == nil {
					primary += fmt.Sprintf("%s=NULL", column.String())
				} else if ok, temporalType := DetectTemporalType(data, column.String()); ok {
					primary += ConvertTemporalOnDelete(temporalType, column.String(), v.Interface())
				} else {
					primary += fmt.Sprintf("%s=%v", column.String(), v.Interface())
				}
				if newType, ok := dataType[column.String()]; ok {
					primary += "::" + newType
				}
			}
		} else {
			for i, column := range columns {
				if i != 0 {
					primary += " AND "
				}
				if reflect.ValueOf(tableMap[column]).Kind() == reflect.String {
					primary += fmt.Sprintf("%s='%v'", column, tableMap[column])
				} else if ok, temporalType := DetectTemporalType(data, column); ok {
					primary += ConvertTemporalOnDelete(temporalType, column, tableMap[column])
				} else {
					primary += fmt.Sprintf("%s=%v", column, tableMap[column])
				}
				if newType, ok := dataType[column]; ok {
					primary += "::" + newType
				}

			}
		}
		Query += fmt.Sprintf("DELETE FROM %s.%s WHERE %s;", schema, table, primary)
	}
	var insert = func() {

		dataType := map[string]string{}
		if isFromSource {
			for _, v := range configs.ModifyDataType {
				dataType[v.Column] = v.NewType
			}
		} else {
			for _, v := range configs.ModifyDataType {
				dataType[v.Column] = v.OldType
			}
		}
		var column string
		var columnValue string
		value := data.Payload.After.(map[string]interface{})
		for key, val := range value {
			column += key + ","
			if val == nil {
				columnValue += "NULL"
			} else {
				if reflect.ValueOf(val).Kind() == reflect.String {
					columnValue += fmt.Sprintf("'%v'", val)
				} else if ok, temporalType := DetectTemporalType(data, key); ok {
					columnValue += ConvertTemporalOnInsert(temporalType, val)
				} else {
					columnValue += fmt.Sprintf("%v", val)
				}

			}
			if newType, ok := dataType[key]; ok {
				columnValue += "::" + newType
			}

			columnValue += ","
		}
		column = strings.TrimSuffix(column, ",")
		columnValue = strings.TrimSuffix(columnValue, ",")
		fmt.Println(dataType)
		Query += fmt.Sprintf("INSERT INTO %s.%s (%s) VALUES (%s);", schema, table, column, columnValue)
	}

	if len(configs.HorizontalSplitting) > 0 {
		horizontalSplit()
	}

	if data.Payload.Op == "d" {
		delete()
	} else if data.Payload.Op == "c" || data.Payload.Op == "r" {
		// if len(configs.ModifyDataType) > 0 {
		// 	insertTransform()
		// } else {
		insert()
		// }
	} else if data.Payload.Op == "u" {
		delete()
		// if len(configs.ModifyDataType) > 0 {
		// 	insertTransform()
		// } else {
		insert()
		// }
	} else if data.Payload.Op == "s" {

	} else {
		fmt.Println(data)
		fmt.Println("Not support this operation")
	}
	// fmt.Println(time.Now().UnixNano())
	return Query
}

func ConvertDataToSQLNormal2(data model.AutoGenerated, primaryKey map[string][]string, configs config.DDLTransform, isFromSource bool, db *sql.DB) string {
	var Query string
	schema := data.Payload.Source.Schema
	table := data.Payload.Source.Table
	columns := primaryKey[fmt.Sprintf("%s.%s", schema, table)]

	var horizontalSplit = func() {
		var partQuery string
		var column string
		var columnValue string
		var value map[string]interface{}
		if data.Payload.Op == "c" {
			value = data.Payload.After.(map[string]interface{})
		} else {
			value = data.Payload.Before.(map[string]interface{})
		}
		for key, val := range value {
			column = key
			if val == nil {
				columnValue = "NULL"
			} else {
				if reflect.ValueOf(val).Kind() == reflect.String {
					columnValue = fmt.Sprintf("'%v'", val)
				} else if ok, temporalType := DetectTemporalType(data, key); ok {
					columnValue = ConvertTemporalOnInsert(temporalType, val)
				} else {
					columnValue = fmt.Sprintf("%v", val)
				}

			}
			partQuery += fmt.Sprintf(" %s as %s,", columnValue, column)

		}
		partQuery = strings.TrimSuffix(partQuery, ",")
		select_query := fmt.Sprintf("SELECT COUNT(*) FROM (SELECT %s) as test where %s;", partQuery, configs.HorizontalSplitting[0].Criteria)
		fmt.Println(select_query)
		var count int
		err := db.QueryRow(select_query).Scan(&count)
		if err != nil {
			log.Fatal(err)
		}
		fmt.Println(count)
		if count > 0 {
			table = configs.HorizontalSplitting[0].DestTable
		}
	}
	var delete = func() {
		dataType := map[string]string{}
		if isFromSource {
			for _, v := range configs.ModifyDataType {
				dataType[v.Column] = v.NewType
			}
		} else {
			for _, v := range configs.ModifyDataType {
				dataType[v.Column] = v.OldType
			}
		}
		var primary string
		tableMap := map[string]interface{}{}
		var value reflect.Value
		if data.Payload.Op == "d" || len(columns) == 0 {
			value = reflect.ValueOf(data.Payload.Before)
		} else {
			value = reflect.ValueOf(data.Payload.After)
		}

		if value.Kind() == reflect.Map {
			keys := value.MapKeys()
			for _, key := range keys {

				tableMap[key.String()] = value.MapIndex(key)
			}
		}
		if len(columns) == 0 {
			keys := value.MapKeys()
			for i, column := range keys {
				v := value.MapIndex(column)
				if i != 0 {
					primary += " AND "
				}
				if reflect.ValueOf(v.Interface()).Kind() == reflect.String {
					primary += fmt.Sprintf("%s='%v'", column.String(), v.Interface())
				} else if v.Interface() == nil {
					primary += fmt.Sprintf("%s=NULL", column.String())
				} else if ok, temporalType := DetectTemporalType(data, column.String()); ok {
					primary += ConvertTemporalOnDelete(temporalType, column.String(), v.Interface())
				} else {
					primary += fmt.Sprintf("%s=%v", column.String(), v.Interface())
				}
				if newType, ok := dataType[column.String()]; ok {
					primary += "::" + newType
				}
			}
		} else {
			for i, column := range columns {
				if i != 0 {
					primary += " AND "
				}
				if reflect.ValueOf(tableMap[column]).Kind() == reflect.String {
					primary += fmt.Sprintf("%s='%v'", column, tableMap[column])
				} else if ok, temporalType := DetectTemporalType(data, column); ok {
					primary += ConvertTemporalOnDelete(temporalType, column, tableMap[column])
				} else {
					primary += fmt.Sprintf("%s=%v", column, tableMap[column])
				}
				if newType, ok := dataType[column]; ok {
					primary += "::" + newType
				}

			}
		}
		Query += fmt.Sprintf("DELETE FROM %s.%s WHERE %s;", schema, table, primary)
	}
	var insert = func() {

		dataType := map[string]string{}
		if isFromSource {
			for _, v := range configs.ModifyDataType {
				dataType[v.Column] = v.NewType
			}
		} else {
			for _, v := range configs.ModifyDataType {
				dataType[v.Column] = v.OldType
			}
		}
		var column string
		var columnValue string
		value := data.Payload.After.(map[string]interface{})
		for key, val := range value {
			column += key + ","
			if val == nil {
				columnValue += "NULL"
			} else {
				if reflect.ValueOf(val).Kind() == reflect.String {
					columnValue += fmt.Sprintf("'%v'", val)
				} else if ok, temporalType := DetectTemporalType(data, key); ok {
					columnValue += ConvertTemporalOnInsert(temporalType, val)
				} else {
					columnValue += fmt.Sprintf("%v", val)
				}

			}
			if newType, ok := dataType[key]; ok {
				columnValue += "::" + newType
			}

			columnValue += ","
		}
		column = strings.TrimSuffix(column, ",")
		columnValue = strings.TrimSuffix(columnValue, ",")
		Query += fmt.Sprintf("INSERT INTO %s.%s (%s) VALUES (%s);", schema, table, column, columnValue)
	}

	if len(configs.HorizontalSplitting) > 0 {
		horizontalSplit()
	}

	if data.Payload.Op == "d" {
		delete()
	} else if data.Payload.Op == "c" || data.Payload.Op == "r" {
		// if len(configs.ModifyDataType) > 0 {
		// 	insertTransform()
		// } else {
		insert()
		// }
	} else if data.Payload.Op == "u" {
		delete()
		// if len(configs.ModifyDataType) > 0 {
		// 	insertTransform()
		// } else {
		insert()
		// }
	} else if data.Payload.Op == "s" {

	} else {
		fmt.Println(data)
		fmt.Println("Not support this operation")
	}
	// fmt.Println(time.Now().UnixNano())
	return Query
}

func ConvertDataToSQLDenormalize(data model.AutoGenerated, configs config.DDLTransform, isFromSource bool, primaryKey string) string {
	var Query string
	// schema := data.Payload.Source.Schema
	// table := data.Payload.Source.Table
	var destTable string

	dataType := map[string]string{}
	if isFromSource {
		for _, v := range configs.ModifyDataType {
			dataType[v.Column] = v.NewType
		}
	} else {
		for _, v := range configs.ModifyDataType {
			dataType[v.Column] = v.OldType
		}
	}
	var column []string
	var columnValue []string
	var value map[string]interface{}
	if data.Payload.Op == "u" || data.Payload.Op == "c" || data.Payload.Op == "r" {
		value = data.Payload.After.(map[string]interface{})
	} else if data.Payload.Op == "d" {
		value = data.Payload.Before.(map[string]interface{})
	}
	for key, val := range value {
		column = append(column, key)
		if val == nil || data.Payload.Op == "d" {
			columnValue = append(columnValue, "NULL")
		} else {
			var columnValueTemp string
			if reflect.ValueOf(val).Kind() == reflect.String {
				columnValueTemp = fmt.Sprintf("'%v'", val)
			} else if ok, temporalType := DetectTemporalType(data, key); ok {
				columnValueTemp = ConvertTemporalOnInsert(temporalType, val)
			} else {
				columnValueTemp = fmt.Sprintf("%v", val)
			}
			if newType, ok := dataType[key]; ok {
				columnValueTemp += "::" + newType
			}
			columnValue = append(columnValue, columnValueTemp)
		}
	}

	if len(configs.CreateTable) > 0 {
		destTable = configs.CreateTable[0].RelatedTable
	}
	if data.Payload.Op == "c" || data.Payload.Op == "r" {
		//Insert if not exists
		insertColumn := strings.Join(column, ",")
		insertColumnValue := strings.Join(columnValue, ",")
		Query += fmt.Sprintf("INSERT INTO %s (%s) SELECT %s WHERE NOT EXISTS (SELECT * FROM %s WHERE %s);", destTable, insertColumn, insertColumnValue, destTable, primaryKey)
	}
	updateStatement := fmt.Sprintf("UPDATE %s set ", destTable)
	for i, col := range column {
		updateStatement += fmt.Sprintf("%s=%s,", col, columnValue[i])
	}
	updateStatement = strings.TrimSuffix(updateStatement, ",")
	Query += updateStatement + fmt.Sprintf(" WHERE %s;", primaryKey)
	return Query
}
func ConvertDataToSQLVerticalSplitting(data model.AutoGenerated, primaryKey map[string][]string, configs config.DDLTransform, db *sql.DB) string {
	var Query string
	var QueryArray []string
	if !configs.VerticalSplitting[0].SourceDeleted {
		QueryArray = append(QueryArray, ConvertDataToSQLNormal(data, primaryKey, configs, true, db))
	}
	for _, table := range configs.VerticalSplitting[0].DerivedTableDetails {
		tempData := data
		if tempData.Payload.After != nil {
			tableMap := tempData.Payload.After.(map[string]interface{})
			usedMap := map[string]interface{}{}

			for _, column := range table.Colname {
				usedMap[column] = tableMap[column]
			}

			tempData.Payload.After = usedMap
		}
		if tempData.Payload.Before != nil {
			tableMap := tempData.Payload.Before.(map[string]interface{})
			usedMap := map[string]interface{}{}

			for _, column := range table.Colname {
				usedMap[column] = tableMap[column]
			}
			tempData.Payload.Before = usedMap
		}
		tempData.Payload.Source.Table = table.Table
		QueryArray = append(QueryArray, ConvertDataToSQLNormal(tempData, primaryKey, configs, true, db))
	}
	Query = strings.Join(QueryArray, "")

	return Query
}

func ExtractColumnAndValueData(data model.AutoGenerated, configs config.DDLTransform, isFromSource bool) (Column, ColumnValue) {
	var column Column
	var columnValue ColumnValue
	var value map[string]interface{}
	dataType := map[string]string{}
	if isFromSource {
		for _, v := range configs.ModifyDataType {
			dataType[v.Column] = v.NewType
		}
	} else {
		for _, v := range configs.ModifyDataType {
			dataType[v.Column] = v.OldType
		}
	}
	if data.Payload.Op == "c" || data.Payload.Op == "u" || data.Payload.Op == "r" {
		value = data.Payload.After.(map[string]interface{})

	} else if data.Payload.Op == "d" {
		value = data.Payload.Before.(map[string]interface{})
	}
	for key, val := range value {
		column = append(column, key)
		if val == nil {
			columnValue = append(columnValue, "NULL")
		} else {
			var columnValueTemp string
			if reflect.ValueOf(val).Kind() == reflect.String {
				columnValueTemp = fmt.Sprintf("'%v'", val)
			} else if ok, temporalType := DetectTemporalType(data, key); ok {
				columnValueTemp = ConvertTemporalOnInsert(temporalType, val)
			} else {
				columnValueTemp = fmt.Sprintf("%v", val)
			}
			if newType, ok := dataType[key]; ok {
				columnValueTemp += "::" + newType
			}
			columnValue = append(columnValue, columnValueTemp)
		}
	}
	return column, columnValue

}
func ConvertDataToSQLVerticalSplittingDest(data model.AutoGenerated, configs config.DDLTransform) string {

	var primaryKey string
	// sourceTable := configs.CreateTable[0].RelatedTable
	primaryKeyList := configs.CreateTable[0].RelatedTablePrimaryKeys
	primaryKeyValue := []string{}
	column, columnValue := ExtractColumnAndValueData(data, configs, false)
	// if data.Payload.Op == "c" || data.Payload.Op == "u" {
	columnMap := map[string]string{}
	for i, v := range column {
		columnMap[v] = columnValue[i]
	}
	for _, v := range primaryKeyList {
		primaryKeyValue = append(primaryKeyValue, v+"="+columnMap[v])
	}
	primaryKey = strings.Join(primaryKeyValue, " AND ")
	return ConvertDataToSQLDenormalize(data, configs, false, primaryKey)
	// }

}

func ConvertDataToSQL(data model.AutoGenerated, primaryKey map[string][]string, configs config.DDLTransform, isFromSource bool, db *sql.DB) string {
	var Query string
	if len(configs.VerticalSplitting) > 0 && isFromSource {
		Query = ConvertDataToSQLVerticalSplitting(data, primaryKey, configs, db)
		// fmt.Println("Option ", 1)
	} else if len(configs.CreateTable) > 0 && configs.CreateTable[0].BeingUsed && !isFromSource {
		Query = ConvertDataToSQLVerticalSplittingDest(data, configs)
		// fmt.Println("Option ", 2)
	} else {
		Query = ConvertDataToSQLNormal(data, primaryKey, configs, isFromSource, db)
		// fmt.Println("Option ", 3)
	}
	return Query
}

// func ConvertDataToSQL(data model.AutoGenerated, primaryKey map[string][]string) string {
// 	var Query string
// 	schema := data.Payload.Source.Schema
// 	table := data.Payload.Source.Table

// 	columns := primaryKey[fmt.Sprintf("%s.%s", schema, table)]
// 	var delete = func() {
// 		var primary string
// 		tableMap := map[string]interface{}{}
// 		var value reflect.Value
// 		if data.Payload.Op == "d" {
// 			value = reflect.ValueOf(data.Payload.Before)
// 		} else {
// 			value = reflect.ValueOf(data.Payload.After)
// 		}

// 		if value.Kind() == reflect.Map {
// 			keys := value.MapKeys()
// 			for _, key := range keys {

// 				tableMap[key.String()] = value.MapIndex(key)
// 			}
// 		}
// 		for i, column := range columns {
// 			if i != 0 {
// 				primary += " AND "
// 			}
// 			if reflect.ValueOf(tableMap[column]).Kind() == reflect.String {
// 				primary += fmt.Sprintf("%s='%v'", column, tableMap[column])
// 			} else {
// 				primary += fmt.Sprintf("%s=%v", column, tableMap[column])
// 			}

// 		}
// 		Query += fmt.Sprintf("DELETE FROM %s.%s WHERE %s;", schema, table, primary)
// 	}
// 	var insert = func() {
// 		type Record struct {
// 			Column string
// 			Value  interface{}
// 		}
// 		records := []Record{}
// 		var column string
// 		var columnValue string
// 		value := reflect.ValueOf(data.Payload.After)
// 		if value.Kind() == reflect.Map {
// 			keys := value.MapKeys()
// 			for _, key := range keys {
// 				v := value.MapIndex(key)
// 				records = append(records, Record{Column: key.String(), Value: v.Interface()})
// 			}
// 		}
// 		for index, record := range records {
// 			column += record.Column + ","
// 			if reflect.ValueOf(record.Value).Kind() == reflect.String {
// 				columnValue += fmt.Sprintf("'%v'", record.Value) + ","
// 			} else if record.Value == nil {
// 				columnValue += "NULL,"
// 			} else if data.Schema.Fields[1].Fields[index].Type == "timestamp" {
// 				columnValue += fmt.Sprintf("'%v'", time.Unix(record.Value.(int64)/1000, 0)) + ","

// 			} else {
// 				columnValue += fmt.Sprintf("%v", record.Value) + ","
// 			}
// 		}
// 		column = strings.TrimSuffix(column, ",")
// 		columnValue = strings.TrimSuffix(columnValue, ",")
// 		Query += fmt.Sprintf("INSERT INTO %s.%s (%s) VALUES (%s);", schema, table, column, columnValue)
// 	}

// 	if data.Payload.Op == "d" {
// 		delete()
// 	} else if data.Payload.Op == "c" || data.Payload.Op == "r" {
// 		insert()
// 	} else if data.Payload.Op == "u" {
// 		delete()
// 		insert()
// 	}
// 	// fmt.Println(time.Now().UnixNano())
// 	return Query
// }
