package utils

import (
	"fmt"
	"reflect"
	"strings"

	"github.com/rweebs/cdc-bowo/internal/app/config"
	"github.com/rweebs/cdc-bowo/internal/app/model"
)

func ConvertDataToSQL(data model.AutoGenerated, primaryKey map[string][]string, configs config.DDLTransform) string {
	var Query string
	schema := data.Payload.Source.Schema
	table := data.Payload.Source.Table

	columns := primaryKey[fmt.Sprintf("%s.%s", schema, table)]
	var delete = func() {
		var primary string
		tableMap := map[string]interface{}{}
		var value reflect.Value
		if data.Payload.Op == "d" || len(columns) == 0 {
			value = reflect.ValueOf(data.Payload.Before)
		} else {
			value = reflect.ValueOf(data.Payload.After)
		}

		if value.Kind() == reflect.Map {
			keys := value.MapKeys()
			for _, key := range keys {

				tableMap[key.String()] = value.MapIndex(key)
			}
		}
		if len(columns) == 0 {
			keys := value.MapKeys()
			for i, key := range keys {
				v := value.MapIndex(key)
				if i != 0 {
					primary += " AND "
				}
				if reflect.ValueOf(v.Interface()).Kind() == reflect.String {
					primary += fmt.Sprintf("%s='%v'", key.String(), v.Interface())
				} else if v.Interface() == nil {
					primary += fmt.Sprintf("%s=NULL,", key.String())
				} else if key.String() == "created" {
					primary += fmt.Sprintf("%s=to_timestamp(%v/1000000)", key.String(), v.Interface())
				} else {
					primary += fmt.Sprintf("%s=%v", key.String(), v.Interface())
				}
			}
		} else {
			for i, column := range columns {
				if i != 0 {
					primary += " AND "
				}
				if reflect.ValueOf(tableMap[column]).Kind() == reflect.String {
					primary += fmt.Sprintf("%s='%v'", column, tableMap[column])
				} else {
					primary += fmt.Sprintf("%s=%v", column, tableMap[column])
				}

			}
		}
		Query += fmt.Sprintf("DELETE FROM %s.%s WHERE %s;", schema, table, primary)
	}
	var insertTransform = func() {

		dataType := map[string]string{}
		for _, v := range configs.ModifyDataType {
			dataType[v.Column] = v.NewType
		}
		var column string
		var columnValue string
		value := data.Payload.After.(map[string]interface{})
		for key, val := range value {
			column += key + ","
			if val == nil {
				columnValue += "NULL"
			} else {
				if reflect.ValueOf(val).Kind() == reflect.String {
					columnValue += fmt.Sprintf("'%v'", val)
				} else {
					columnValue += fmt.Sprintf("%v", val)
				}
			}
			if newType, ok := dataType[key]; ok {
				columnValue += "::" + newType
			}

			columnValue += ","
		}
		column = strings.TrimSuffix(column, ",")
		columnValue = strings.TrimSuffix(columnValue, ",")
		Query += fmt.Sprintf("INSERT INTO %s.%s (%s) VALUES (%s);", schema, table, column, columnValue)
	}
	var insert = func() {
		type Record struct {
			Column string
			Value  interface{}
		}
		records := []Record{}
		var column string
		var columnValue string
		value := reflect.ValueOf(data.Payload.After)
		if value.Kind() == reflect.Map {
			keys := value.MapKeys()
			for _, key := range keys {
				v := value.MapIndex(key)
				records = append(records, Record{Column: key.String(), Value: v.Interface()})
				// if v.Kind() == reflect.Int64 {
				// 	fmt.Println(v.String())
				// 	fmt.Println(v.Kind())
				// }
			}
		}
		for _, record := range records {
			column += record.Column + ","
			if reflect.ValueOf(record.Value).Kind() == reflect.String {
				columnValue += fmt.Sprintf("'%v'", record.Value) + ","
			} else if record.Value == nil {
				columnValue += "NULL,"
			} else if record.Column == "created" {
				columnValue += fmt.Sprintf("to_timestamp(%v/1000000)", record.Value) + ","
			} else {
				columnValue += fmt.Sprintf("%v", record.Value) + ","
			}
		}
		column = strings.TrimSuffix(column, ",")
		columnValue = strings.TrimSuffix(columnValue, ",")
		Query += fmt.Sprintf("INSERT INTO %s.%s (%s) VALUES (%s);", schema, table, column, columnValue)
	}

	if data.Payload.Op == "d" {
		delete()
	} else if data.Payload.Op == "c" || data.Payload.Op == "r" {
		if len(configs.ModifyDataType) > 0 {
			insertTransform()
		} else {
			insert()
		}
	} else if data.Payload.Op == "u" {
		delete()
		if len(configs.ModifyDataType) > 0 {
			insertTransform()
		} else {
			insert()
		}
	} else {
		fmt.Println(data)
		fmt.Println("Not support this operation")
	}
	// fmt.Println(time.Now().UnixNano())
	return Query
}

// func ConvertDataToSQL(data model.AutoGenerated, primaryKey map[string][]string) string {
// 	var Query string
// 	schema := data.Payload.Source.Schema
// 	table := data.Payload.Source.Table

// 	columns := primaryKey[fmt.Sprintf("%s.%s", schema, table)]
// 	var delete = func() {
// 		var primary string
// 		tableMap := map[string]interface{}{}
// 		var value reflect.Value
// 		if data.Payload.Op == "d" {
// 			value = reflect.ValueOf(data.Payload.Before)
// 		} else {
// 			value = reflect.ValueOf(data.Payload.After)
// 		}

// 		if value.Kind() == reflect.Map {
// 			keys := value.MapKeys()
// 			for _, key := range keys {

// 				tableMap[key.String()] = value.MapIndex(key)
// 			}
// 		}
// 		for i, column := range columns {
// 			if i != 0 {
// 				primary += " AND "
// 			}
// 			if reflect.ValueOf(tableMap[column]).Kind() == reflect.String {
// 				primary += fmt.Sprintf("%s='%v'", column, tableMap[column])
// 			} else {
// 				primary += fmt.Sprintf("%s=%v", column, tableMap[column])
// 			}

// 		}
// 		Query += fmt.Sprintf("DELETE FROM %s.%s WHERE %s;", schema, table, primary)
// 	}
// 	var insert = func() {
// 		type Record struct {
// 			Column string
// 			Value  interface{}
// 		}
// 		records := []Record{}
// 		var column string
// 		var columnValue string
// 		value := reflect.ValueOf(data.Payload.After)
// 		if value.Kind() == reflect.Map {
// 			keys := value.MapKeys()
// 			for _, key := range keys {
// 				v := value.MapIndex(key)
// 				records = append(records, Record{Column: key.String(), Value: v.Interface()})
// 			}
// 		}
// 		for index, record := range records {
// 			column += record.Column + ","
// 			if reflect.ValueOf(record.Value).Kind() == reflect.String {
// 				columnValue += fmt.Sprintf("'%v'", record.Value) + ","
// 			} else if record.Value == nil {
// 				columnValue += "NULL,"
// 			} else if data.Schema.Fields[1].Fields[index].Type == "timestamp" {
// 				columnValue += fmt.Sprintf("'%v'", time.Unix(record.Value.(int64)/1000, 0)) + ","

// 			} else {
// 				columnValue += fmt.Sprintf("%v", record.Value) + ","
// 			}
// 		}
// 		column = strings.TrimSuffix(column, ",")
// 		columnValue = strings.TrimSuffix(columnValue, ",")
// 		Query += fmt.Sprintf("INSERT INTO %s.%s (%s) VALUES (%s);", schema, table, column, columnValue)
// 	}

// 	if data.Payload.Op == "d" {
// 		delete()
// 	} else if data.Payload.Op == "c" || data.Payload.Op == "r" {
// 		insert()
// 	} else if data.Payload.Op == "u" {
// 		delete()
// 		insert()
// 	}
// 	// fmt.Println(time.Now().UnixNano())
// 	return Query
// }
