package utils

import (
	"strings"

	"github.com/rweebs/cdc-bowo/src/internal/app/config"
	"github.com/rweebs/cdc-bowo/src/internal/app/model"
)

func AddColumn(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
	// if data.Payload.After != nil {
	// 	tableMap := data.Payload.After.(map[string]interface{})
	// 	for _, v := range config.AddColumn {
	// 		if v.IsNullable {
	// 			tableMap[v.Column] = nil
	// 		} else {
	// 			tableMap[v.Column] = v.Default
	// 		}
	// 	}

	// 	data.Payload.After = tableMap
	// }
	// if data.Payload.Before != nil {
	// 	tableMapBefore := data.Payload.Before.(map[string]interface{})
	// 	for _, v := range config.AddColumn {
	// 		if v.IsNullable {
	// 			tableMapBefore[v.Column] = nil
	// 		} else {
	// 			tableMapBefore[v.Column] = v.Default
	// 		}
	// 	}
	// 	data.Payload.Before = tableMapBefore
	// }
	return data
}

func AddColumnDest(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
	if data.Payload.After != nil {
		tableMapAfter := data.Payload.After.(map[string]interface{})
		for _, v := range config.AddColumn {
			delete(tableMapAfter, v.Column)
		}
		data.Payload.After = tableMapAfter
	}
	if data.Payload.Before != nil {
		tableMapBefore := data.Payload.Before.(map[string]interface{})
		for _, v := range config.AddColumn {
			delete(tableMapBefore, v.Column)
		}
		data.Payload.Before = tableMapBefore
	}
	return data
}

func DropColumn(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
	if data.Payload.After != nil {
		tableMap := data.Payload.After.(map[string]interface{})
		for _, v := range config.DropColumn {
			delete(tableMap, v.Column)
		}
		data.Payload.After = tableMap
	}
	if data.Payload.Before != nil {
		tableMapBefore := data.Payload.Before.(map[string]interface{})
		for _, v := range config.DropColumn {
			delete(tableMapBefore, v.Column)
		}
		data.Payload.Before = tableMapBefore
	}
	return data
}

func DropColumnDest(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
	if data.Payload.After != nil {
		tableMap := data.Payload.After.(map[string]interface{})
		for _, v := range config.DropColumn {
			if v.IsNullable {
				tableMap[v.Column] = nil
			} else {
				tableMap[v.Column] = v.Default
			}
		}

		data.Payload.After = tableMap
	}
	if data.Payload.Before != nil {
		tableMapBefore := data.Payload.Before.(map[string]interface{})
		for _, v := range config.DropColumn {
			if v.IsNullable {
				tableMapBefore[v.Column] = nil
			} else {
				tableMapBefore[v.Column] = v.Default
			}
		}
		data.Payload.Before = tableMapBefore
	}
	return data
}
func CreateTableDest(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
	data.Payload.Op = "s"
	return data
}

func DropTable(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
	data.Payload.Op = "s"
	return data
}

func RenameTable(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
	for _, v := range config.RenameTable {
		data.Payload.Source.Table = v.NewName
	}
	return data
}

func RenameTableDest(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
	for _, v := range config.RenameTable {
		data.Payload.Source.Table = v.OldName
	}
	return data
}
func RenameColumn(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
	if data.Payload.After != nil {
		tableMap := data.Payload.After.(map[string]interface{})
		dats := data.Schema.Fields[1].Fields
		for _, v := range config.RenameColumn {
			tableMap[v.NewName] = tableMap[v.OldName]
			delete(tableMap, v.OldName)
			for i := range dats {
				if dats[i].Field == v.OldName {
					dats[i].Field = v.NewName
				}
			}
		}
		data.Payload.After = tableMap
		data.Schema.Fields[1].Fields = dats
	}
	if data.Payload.Before != nil {
		tableMapBefore := data.Payload.Before.(map[string]interface{})
		dats := data.Schema.Fields[1].Fields
		for _, v := range config.RenameColumn {
			tableMapBefore[v.NewName] = tableMapBefore[v.OldName]
			delete(tableMapBefore, v.OldName)
			for i := range dats {
				if dats[i].Field == v.OldName {
					dats[i].Field = v.NewName
				}
			}
		}
		data.Payload.Before = tableMapBefore
		data.Schema.Fields[1].Fields = dats
	}
	return data
}

func RenameColumnDest(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
	dataSchemaFields := data.Schema.Fields[1].Fields

	for _, v := range config.RenameColumn {
		for i := range dataSchemaFields {
			if dataSchemaFields[i].Field == v.NewName {
				dataSchemaFields[i].Field = v.OldName
			}
		}
	}
	data.Schema.Fields[1].Fields = dataSchemaFields
	if data.Payload.After != nil {
		tableMap := data.Payload.After.(map[string]interface{})
		dats := data.Schema.Fields[1].Fields
		for _, v := range config.RenameColumn {
			tableMap[v.OldName] = tableMap[v.NewName]
			delete(tableMap, v.NewName)
			for i := range dats {
				if dats[i].Field == v.NewName {
					dats[i].Field = v.OldName
				}
			}

		}
		data.Payload.After = tableMap
		data.Schema.Fields[1].Fields = dats
	}
	if data.Payload.Before != nil {
		tableMapBefore := data.Payload.Before.(map[string]interface{})
		dats := data.Schema.Fields[1].Fields
		for _, v := range config.RenameColumn {
			tableMapBefore[v.OldName] = tableMapBefore[v.NewName]
			delete(tableMapBefore, v.NewName)
			for i := range dats {
				if dats[i].Field == v.NewName {
					dats[i].Field = v.OldName
				}
			}
		}
		data.Payload.Before = tableMapBefore
		data.Schema.Fields[1].Fields = dats
	}
	return data
}

func DebeziumPostgresTemporalMap() map[string]string {
	return map[string]string{
		"date":         "io.debezium.time.Date",
		"time":         "io.debezium.time.MicroTime",
		"time(1)":      "io.debezium.time.Time",
		"time(2)":      "io.debezium.time.Time",
		"time(3)":      "io.debezium.time.Time",
		"time(4)":      "io.debezium.time.MicroTime",
		"time(5)":      "io.debezium.time.MicroTime",
		"time(6)":      "io.debezium.time.MicroTime",
		"timestamp":    "io.debezium.time.MicroTimestamp",
		"timestamp(1)": "io.debezium.time.Timestamp",
		"timestamp(2)": "io.debezium.time.Timestamp",
		"timestamp(3)": "io.debezium.time.Timestamp",
		"timestamp(4)": "io.debezium.time.MicroTimestamp",
		"timestamp(5)": "io.debezium.time.MicroTimestamp",
		"timestamp(6)": "io.debezium.time.MicroTimestamp",
	}
}
func ConvertTemporalDataTypeDest(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
	dataSchemaFields := data.Schema.Fields[1].Fields
	for _, v := range config.ModifyDataType {
		for i := range dataSchemaFields {
			if dataSchemaFields[i].Field == v.Column {
				newTypeRemoveWhiteSpace := strings.ReplaceAll(v.NewType, " ", "")
				newTypeToLower := strings.ToLower(newTypeRemoveWhiteSpace)
				if debeziumType, ok := DebeziumPostgresTemporalMap()[newTypeToLower]; ok {
					dataSchemaFields[i].Type = debeziumType
				}
			}
		}
	}
	data.Schema.Fields[1].Fields = dataSchemaFields
	return data
}

//	func HorizontalSplittingDest(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
//		for _, v := range config.HorizontalSplitting {
//			data.Payload.Source.Table = v.
//		}
//		return data
//	}
func ConvertSchema(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
	if len(config.DropTable) > 0 {
		data = DropTable(data, config)
		return data
	}
	if len(config.RenameTable) > 0 {
		data = RenameTable(data, config)
	}
	if len(config.RenameColumn) > 0 {
		data = RenameColumn(data, config)
	}
	if len(config.DropColumn) > 0 {
		data = DropColumn(data, config)
	}
	if len(config.AddColumn) > 0 {
		data = AddColumn(data, config)
	}
	// if len(config.HorizontalSplitting) > 0 {
	// 	data = HorizontalSplitting(data, config)
	// }
	// data2, _ := json.MarshalIndent(data, "", "  ")
	// fmt.Println(string(data2))
	return data
}

func ConvertSchemaDest(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
	if len(config.CreateTable) > 0 {
		if !config.CreateTable[0].BeingUsed {
			data = CreateTableDest(data, config)
		}
		return data
	}
	if len(config.RenameTable) > 0 {
		data = RenameTableDest(data, config)
	}
	if len(config.RenameColumn) > 0 {
		data = RenameColumnDest(data, config)
	}
	if len(config.DropColumn) > 0 {
		data = DropColumnDest(data, config)
	}
	if len(config.AddColumn) > 0 {
		data = AddColumnDest(data, config)
	}
	// if len(config.ModifyDataType) > 0 {
	// 	data = ConvertTemporalDataTypeDest(data, config)
	// }
	return data
}
