package utils

import (
	"strings"

	"github.com/rweebs/cdc-bowo/internal/app/config"
	"github.com/rweebs/cdc-bowo/internal/app/model"
)

func AddColumn(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
	// if data.Payload.After != nil {
	// 	tableMap := data.Payload.After.(map[string]interface{})
	// 	for _, v := range config.AddColumn {
	// 		if v.IsNullable {
	// 			tableMap[v.Column] = nil
	// 		} else {
	// 			tableMap[v.Column] = v.Default
	// 		}
	// 	}

	// 	data.Payload.After = tableMap
	// }
	// if data.Payload.Before != nil {
	// 	tableMapBefore := data.Payload.Before.(map[string]interface{})
	// 	for _, v := range config.AddColumn {
	// 		if v.IsNullable {
	// 			tableMapBefore[v.Column] = nil
	// 		} else {
	// 			tableMapBefore[v.Column] = v.Default
	// 		}
	// 	}
	// 	data.Payload.Before = tableMapBefore
	// }
	return data
}

// AddColumnDest modifies the data to add columns. This is a copy of tableMap. AddColumn that is used for migration.
//
// Args:
//
//	data: The data to modify. The modified data is returned.
//	config: The configuration for the table that is being migrated
func AddColumnDest(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
	// data. Payload. After is a map string interface interface
	if data.Payload.After != nil {
		tableMapAfter := data.Payload.After.(map[string]interface{})

		// Delete the tableMapAfter tableMapAfter. Column.
		for _, v := range config.AddColumn {
			delete(tableMapAfter, v.Column)
		}
		data.Payload.After = tableMapAfter
	}
	// data. Payload. Before is a map string interface interface
	if data.Payload.Before != nil {
		tableMapBefore := data.Payload.Before.(map[string]interface{})
		// Delete the tableMapBefore and tableMapAfter. Column
		for _, v := range config.AddColumn {
			delete(tableMapBefore, v.Column)
		}
		data.Payload.Before = tableMapBefore
	}
	return data
}

// DropColumn removes column from DDL. Note that after and before are mutually exclusive. In the case of dropping a column we need to make sure there is no reference to the column before and after.
//
// Args:
//
//	data: The data that was auto generated. The processed data is returned for convenience.
//	config: The configuration for the transform that will be used
func DropColumn(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
	// Drop column names from the payload.
	if data.Payload.After != nil {
		tableMap := data.Payload.After.(map[string]interface{})

		// Delete all columns from the tableMap.

		for _, v := range config.DropColumn {
			delete(tableMap, v.Column)
		}
		data.Payload.After = tableMap
	}

	// Drop column names from the payload.
	if data.Payload.Before != nil {
		tableMapBefore := data.Payload.Before.(map[string]interface{})

		// Delete all columns from the tableMapBefore.
		for _, v := range config.DropColumn {
			delete(tableMapBefore, v.Column)
		}
		data.Payload.Before = tableMapBefore
	}
	return data
}

// DropColumnDest drops columns from table. The drop column is used to create a column that doesn t exist in the table.
//
// Args:
//
//	data: The data which was auto generated. The modified data is returned.
//	config: The configuration for the model which contains the DDLTransform
func DropColumnDest(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
	// Set the data. Payload. After field to the data. Payload. After.
	if data.Payload.After != nil {
		tableMap := data.Payload.After.(map[string]interface{})
		// Set the default value of drop column
		for _, v := range config.DropColumn {
			// Set the default value of the column.
			if v.IsNullable {
				tableMap[v.Column] = nil
			} else {
				tableMap[v.Column] = v.Default
			}
		}

		data.Payload.After = tableMap
	}
	// Set the data. Payload. Before to the map of column names to default values.
	if data.Payload.Before != nil {
		tableMapBefore := data.Payload.Before.(map[string]interface{})
		// Set the column to the default value if any of the drop columns is nullable.
		for _, v := range config.DropColumn {
			// Set the column to the default value.
			if v.IsNullable {
				tableMapBefore[v.Column] = nil
			} else {
				tableMapBefore[v.Column] = v.Default
			}
		}
		data.Payload.Before = tableMapBefore
	}
	return data
}

// CreateTableDest creates table destination. See CreateTable for more details. TODO ( yifan ) : Rename this to create_table
//
// Args:
//
//	data: The data in which the operation will be applied.
//	config: The configuration for the transform which is currently being used
func CreateTableDest(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
	data.Payload.Op = "s"
	return data
}

// DropTable drops table from database. Note that we don t support DROP TABLE in mysql. This is a no op and will be removed in v1.
//
// Args:
//
//	data: The auto generated payload.
//	config: The config for the transform which is currently being used
func DropTable(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
	data.Payload.Op = "s"
	return data
}

// RenameTable renames table in DDL. TODO ( dimitern ) : RenameTable should be moved to model.
//
// Args:
//
//	data: The data used to generate the schema.
//	config: The configuration for the transform which is used to get the list of columns to rename
func RenameTable(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
	// RenameTable is a list of table names
	for _, v := range config.RenameTable {
		data.Payload.Source.Table = v.NewName
	}
	return data
}

// RenameTableDest renames the table after migration. TODO ( dimitern ) : Rename this to a more user friendly name
//
// Args:
//
//	data: The data in which the payload will be modified.
//	config: The configuration for the transform which is currently processing
func RenameTableDest(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
	// RenameTable is a list of table names that are renamed to the old name
	for _, v := range config.RenameTable {
		data.Payload.Source.Table = v.OldName
	}
	return data
}

// Alter column name in after and before schema. This is to support rename column in DDLTransform. The data. Payload should be modified as needed
//
// Args:
//
//	data: The data being processed.
//	config: The configuration for the transformation which is used to determine how to rename
func RenameColumn(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
	// This method is used to remove the column names from the payload.
	if data.Payload.After != nil {
		tableMap := data.Payload.After.(map[string]interface{})
		dats := data.Schema.Fields[1].Fields
		// RenameColumn. NewName and oldName are removed from tableMap
		for _, v := range config.RenameColumn {
			tableMap[v.NewName] = tableMap[v.OldName]
			delete(tableMap, v.OldName)
			// Set the old name to the new name
			for i := range dats {
				// Set the field of the column to the new name
				if dats[i].Field == v.OldName {
					dats[i].Field = v.NewName
				}
			}
		}
		data.Payload.After = tableMap
		data.Schema.Fields[1].Fields = dats
	}
	// data. Payload. Before is not nil.
	if data.Payload.Before != nil {
		tableMapBefore := data.Payload.Before.(map[string]interface{})
		dats := data.Schema.Fields[1].Fields
		// RenameColumn. NewName and oldName are removed from tableMapBefore
		for _, v := range config.RenameColumn {
			tableMapBefore[v.NewName] = tableMapBefore[v.OldName]
			delete(tableMapBefore, v.OldName)
			// Set the old name to the new name
			for i := range dats {
				// Set the field of the column to the new name
				if dats[i].Field == v.OldName {
					dats[i].Field = v.NewName
				}
			}
		}
		data.Payload.Before = tableMapBefore
		data.Schema.Fields[1].Fields = dats
	}
	return data
}

// RenameColumnDest renames columns in data schema. The renaming is done in a DDLTransform field.
//
// Args:
//
//	data: The data to update. Should be an auto generated type with schema. Fields [ 1 ] field.
//	config: The configuration for the DDLTransform that was used
func RenameColumnDest(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
	dataSchemaFields := data.Schema.Fields[1].Fields

	// RenameColumn. NewName is the old name of the column
	for _, v := range config.RenameColumn {
		// This function is used to set the old name of the dataSchemaFields
		for i := range dataSchemaFields {
			// This method is used to set the name of the field in the dataSchemaFields array.
			if dataSchemaFields[i].Field == v.NewName {
				dataSchemaFields[i].Field = v.OldName
			}
		}
	}
	data.Schema.Fields[1].Fields = dataSchemaFields
	// This method is used to remove the old names from the payload.
	if data.Payload.After != nil {
		tableMap := data.Payload.After.(map[string]interface{})
		dats := data.Schema.Fields[1].Fields
		// RenameColumn. NewName is the old name of the column.
		for _, v := range config.RenameColumn {
			tableMap[v.OldName] = tableMap[v.NewName]
			delete(tableMap, v.NewName)
			// Set the old name to the old name
			for i := range dats {
				// Set the field to the old name
				if dats[i].Field == v.NewName {
					dats[i].Field = v.OldName
				}
			}

		}
		data.Payload.After = tableMap
		data.Schema.Fields[1].Fields = dats
	}
	// data. Payload. Before is not nil.
	if data.Payload.Before != nil {
		tableMapBefore := data.Payload.Before.(map[string]interface{})
		dats := data.Schema.Fields[1].Fields
		// RenameColumn. NewName is the old name of the column.
		for _, v := range config.RenameColumn {
			tableMapBefore[v.OldName] = tableMapBefore[v.NewName]
			delete(tableMapBefore, v.NewName)
			// Set the old name to the old name
			for i := range dats {
				// Set the field to the old name
				if dats[i].Field == v.NewName {
					dats[i].Field = v.OldName
				}
			}
		}
		data.Payload.Before = tableMapBefore
		data.Schema.Fields[1].Fields = dats
	}
	return data
}

// DebeziumPostgresTemporalMap returns a map of date time and timestamp for use in Postgres
func DebeziumPostgresTemporalMap() map[string]string {
	return map[string]string{
		"date":         "io.debezium.time.Date",
		"time":         "io.debezium.time.MicroTime",
		"time(1)":      "io.debezium.time.Time",
		"time(2)":      "io.debezium.time.Time",
		"time(3)":      "io.debezium.time.Time",
		"time(4)":      "io.debezium.time.MicroTime",
		"time(5)":      "io.debezium.time.MicroTime",
		"time(6)":      "io.debezium.time.MicroTime",
		"timestamp":    "io.debezium.time.MicroTimestamp",
		"timestamp(1)": "io.debezium.time.Timestamp",
		"timestamp(2)": "io.debezium.time.Timestamp",
		"timestamp(3)": "io.debezium.time.Timestamp",
		"timestamp(4)": "io.debezium.time.MicroTimestamp",
		"timestamp(5)": "io.debezium.time.MicroTimestamp",
		"timestamp(6)": "io.debezium.time.MicroTimestamp",
	}
}

// ConvertTemporalDataTypeDest converts data type from Postgres temporal to Debezium. This is needed to be able to handle dates and times as well as date.
//
// Args:
//
//	data: The data type in auto generated format. This is modified in place.
//	config: The transform configuration that contains information about how to convert the data type
func ConvertTemporalDataTypeDest(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
	dataSchemaFields := data.Schema.Fields[1].Fields
	// Modify data type for the current modify data type.
	for _, v := range config.ModifyDataType {
		// This function will remove any whitespace from the column name.
		for i := range dataSchemaFields {
			// If the column is a column and the column is a debezium postgres temporal map it will be set to the debezium type.
			if dataSchemaFields[i].Field == v.Column {
				newTypeRemoveWhiteSpace := strings.ReplaceAll(v.NewType, " ", "")
				newTypeToLower := strings.ToLower(newTypeRemoveWhiteSpace)
				// Set the type of the data schema
				if debeziumType, ok := DebeziumPostgresTemporalMap()[newTypeToLower]; ok {
					dataSchemaFields[i].Type = debeziumType
				}
			}
		}
	}
	data.Schema.Fields[1].Fields = dataSchemaFields
	return data
}

// ConvertSchema converts schema from auto generated schema to database schema. See model. DDLTransform for details.
//
// Args:
//
//	data: The data to convert. This is expected to be a pointer to a struct so it can be type asserted.
//	config: The configuration for the conversion. This is expected to be a pointer to a struct so it can be type asserted
func ConvertSchema(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
	// Drop table if there is any drop table
	if len(config.DropTable) > 0 {
		data = DropTable(data, config)
		return data
	}
	// Rename table if any.
	if len(config.RenameTable) > 0 {
		data = RenameTable(data, config)
	}
	// Rename the column in the data.
	if len(config.RenameColumn) > 0 {
		data = RenameColumn(data, config)
	}
	// Drop the column if any.
	if len(config.DropColumn) > 0 {
		data = DropColumn(data, config)
	}
	// Add a column to the data.
	if len(config.AddColumn) > 0 {
		data = AddColumn(data, config)
	}
	// if len(config.HorizontalSplitting) > 0 {
	// 	data = HorizontalSplitting(data, config)
	// }
	// data2, _ := json.MarshalIndent(data, "", "  ")
	// log.Println(string(data2))
	return data
}

// ConvertSchemaDest converts schema data from schema format to client format. This function is called after the data has been read from the server and before it is written to the database
//
// Args:
//
//	data: the data read from the server
//	config: the configuration for the schema to be used in
func ConvertSchemaDest(data model.AutoGenerated, config config.DDLTransform) model.AutoGenerated {
	// Create table if needed. If the table is not already created create it.
	if len(config.CreateTable) > 0 {
		// Create table if it s not already used.
		if !config.CreateTable[0].BeingUsed {
			data = CreateTableDest(data, config)
		}
		return data
	}
	// Rename table if the config. RenameTable is set to true
	if len(config.RenameTable) > 0 {
		data = RenameTableDest(data, config)
	}
	// Rename the column if any.
	if len(config.RenameColumn) > 0 {
		data = RenameColumnDest(data, config)
	}
	// Drop the column if any.
	if len(config.DropColumn) > 0 {
		data = DropColumnDest(data, config)
	}
	// Add a column to the data.
	if len(config.AddColumn) > 0 {
		data = AddColumnDest(data, config)
	}
	// if len(config.ModifyDataType) > 0 {
	// 	data = ConvertTemporalDataTypeDest(data, config)
	// }
	return data
}
