package utils

import (
	"database/sql"
	"fmt"
	"log"
	"reflect"
	"strings"
	"time"

	"github.com/rweebs/cdc-bowo/internal/app/config"
	"github.com/rweebs/cdc-bowo/internal/app/model"
)

type Column struct {
	Before []string
	After  []string
}

type ColumnValue struct {
	Before []string
	After  []string
}

func DetectTemporalType(data model.AutoGenerated, key string) (bool, string) {
	// debeziumTimeMap := map[string]bool{"io.debe"}
	var temporalType bool
	var temporalTypeString string

	for _, data := range data.Schema.Fields[1].Fields {
		if data.Field == key {
			return data.Name == "io.debezium.time.MicroTimestamp" || data.Name == "io.debezium.time.Timestamp" || data.Name == "io.debezium.time.Date" || data.Name == "io.debezium.time.MicroTime" || data.Name == "io.debezium.time.Time", data.Name
		}
	}
	return temporalType, temporalTypeString
}
func ConvertTemporalOnInsert(key string, value interface{}) string {
	var result string
	if key == "io.debezium.time.MicroTimestamp" {
		// log.Println(key, value)
		result = fmt.Sprintf("'%s'", time.Unix(0, int64(value.(float64))*1000).UTC().Format(time.RFC3339Nano))
	}
	if key == "io.debezium.time.Timestamp" {
		// log.Println(key, value)
		result = fmt.Sprintf("'%s'", time.Unix(0, int64(value.(float64))*1000000).UTC().Format(time.RFC3339Nano))
	}
	if key == "io.debezium.time.Date" {
		date := time.Unix(int64(value.(float64))*86400, 0).UTC().Format("2006-01-02")
		result = fmt.Sprintf("'%s'", date)
	}
	if key == "io.debezium.time.MicroTime" {

		result = fmt.Sprintf("'%s'", time.Unix(0, int64(value.(float64))*1000).UTC().Format("15:04:05.000000"))
	}
	if key == "io.debezium.time.Time" {
		result = fmt.Sprintf("'%s'", time.Unix(0, int64(value.(float64))*1000000).UTC().Format("15:04:05.000000"))
	}

	return result
}
func ConvertTemporalOnDelete(key string, column string, value interface{}) string {
	var result string
	if key == "io.debezium.time.MicroTimestamp" {
		result = fmt.Sprintf("%s='%s'", column, time.Unix(0, int64(value.(float64))*1000).UTC().Format(time.RFC3339Nano))
	}
	if key == "io.debezium.time.Timestamp" {
		result = fmt.Sprintf("%s='%s'", column, time.Unix(0, int64(value.(float64))*1000000).UTC().Format(time.RFC3339Nano))
	}
	if key == "io.debezium.time.Date" {
		date := time.Unix(int64(value.(float64))*86400, 0).UTC().Format("2006-01-02")
		result = fmt.Sprintf("%s='%s'", column, date)
	}
	if key == "io.debezium.time.MicroTime" {
		result = fmt.Sprintf("%s='%s'", column, time.Unix(0, int64(value.(float64))*1000).UTC().Format("15:04:05.000000"))
	}
	if key == "io.debezium.time.Time" {
		result = fmt.Sprintf("%s='%s'", column, time.Unix(0, int64(value.(float64))*1000000).UTC().Format("15:04:05.000000"))
	}
	return result
}

func ConvertDataToSQLNormal(data model.AutoGenerated, primaryKey map[string][]string, configs config.DDLTransform, isFromSource bool, db *sql.DB) string {
	var Query string
	schema := data.Payload.Source.Schema
	table := data.Payload.Source.Table
	primaryKeyList := primaryKey[fmt.Sprintf("%s.%s", schema, table)]
	column, columnValue := ExtractColumnAndValueData(data, configs, isFromSource)
	var horizontalSplit = func() {
		var partQuery string
		var selectedColumn []string
		var selectedColumnValue []string
		if data.Payload.Op == "c" || data.Payload.Op == "r" {
			selectedColumn = column.After
			selectedColumnValue = columnValue.After
		} else {
			selectedColumn = column.Before
			selectedColumnValue = columnValue.Before
		}
		for i, column := range selectedColumn {
			partQuery += fmt.Sprintf(" %s as %s,", selectedColumnValue[i], column)
		}
		partQuery = strings.TrimSuffix(partQuery, ",")
		select_query := fmt.Sprintf("SELECT COUNT(*) FROM (SELECT %s) as test where %s;", partQuery, configs.HorizontalSplitting[0].Criteria)
		// log.Println(select_query)
		var count int
		err := db.QueryRow(select_query).Scan(&count)
		if err != nil {
			log.Fatal(err)
		}
		// log.Println(count)
		if count > 0 {
			table = configs.HorizontalSplitting[0].DestTable
		}
	}
	var delete = func() {
		var primary string
		if len(primaryKeyList) == 0 {
			for i, column := range column.Before {
				if i != 0 {
					primary += " AND "
				}
				if columnValue.Before[i] == "NULL" {
					primary += fmt.Sprintf("%s ISNULL", column)
				} else {
					primary += fmt.Sprintf("%s=%v", column, columnValue.Before[i])
				}
			}
		} else {
			columnMap := map[string]string{}
			for i, v := range column.Before {
				columnMap[v] = columnValue.Before[i]
			}
			if len(column.Before) == 0 {
				for i, v := range column.After {
					columnMap[v] = columnValue.After[i]
				}
			}
			for i, v := range primaryKeyList {
				if i != 0 {
					primary += " AND "
				}
				primary += fmt.Sprintf("%s=%s", v, columnMap[v])

			}
		}
		Query += fmt.Sprintf("DELETE FROM %s.%s WHERE %s;", schema, table, primary)
	}
	var insert = func() {

		insertColumn := strings.Join(column.After, ",")
		insertColumnValue := strings.Join(columnValue.After, ",")
		Query += fmt.Sprintf("INSERT INTO %s.%s (%s) VALUES (%s);", schema, table, insertColumn, insertColumnValue)
	}

	if len(configs.HorizontalSplitting) > 0 {
		horizontalSplit()
	}

	if data.Payload.Op == "d" {
		delete()
	} else if data.Payload.Op == "c" || data.Payload.Op == "r" {
		insert()
	} else if data.Payload.Op == "u" {
		delete()
		insert()
	} else if data.Payload.Op == "s" {

	} else {
		log.Println(data)
		log.Println("Not support this operation")
	}
	return Query
}

func ConvertDataToSQLVerticalSplitting(data model.AutoGenerated, primaryKey map[string][]string, configs config.DDLTransform, db *sql.DB) string {
	var Query string
	var QueryArray []string
	if !configs.VerticalSplitting[0].SourceDeleted {
		QueryArray = append(QueryArray, ConvertDataToSQLNormal(data, primaryKey, configs, true, db))
	}
	for _, table := range configs.VerticalSplitting[0].DerivedTableDetails {
		tempData := data
		if tempData.Payload.After != nil {
			tableMap := tempData.Payload.After.(map[string]interface{})
			usedMap := map[string]interface{}{}

			for _, column := range table.Colname {
				usedMap[column] = tableMap[column]
			}

			tempData.Payload.After = usedMap
		}
		if tempData.Payload.Before != nil {
			tableMap := tempData.Payload.Before.(map[string]interface{})
			usedMap := map[string]interface{}{}

			for _, column := range table.Colname {
				usedMap[column] = tableMap[column]
			}
			tempData.Payload.Before = usedMap
		}
		tempData.Payload.Source.Table = table.Table
		sourceTable := fmt.Sprintf("%s.%s", data.Payload.Source.Schema, data.Payload.Source.Table)
		derivedTable := fmt.Sprintf("%s.%s", table.Schema, table.Table)
		primaryKey[derivedTable] = primaryKey[sourceTable]
		QueryArray = append(QueryArray, ConvertDataToSQLNormal(tempData, primaryKey, configs, true, db))
	}
	Query = strings.Join(QueryArray, "")

	return Query
}
func IsInArray(value string, array []string) bool {
	for _, v := range array {
		if v == value {
			return true
		}
	}
	return false
}
func RemovePrimaryKeyFromColumnAndColumnValue(column Column, columnValue ColumnValue, primaryKey []string) (Column, ColumnValue) {
	var newColumn Column
	var newColumnValue ColumnValue
	for i, v := range column.After {
		if !IsInArray(v, primaryKey) {
			newColumn.After = append(newColumn.After, v)
			newColumnValue.After = append(newColumnValue.After, columnValue.After[i])
		}
	}
	for i, v := range column.Before {
		if !IsInArray(v, primaryKey) {
			newColumn.Before = append(newColumn.Before, v)
			newColumnValue.Before = append(newColumnValue.Before, columnValue.Before[i])
		}
	}
	return newColumn, newColumnValue
}

func ExtractColumnAndValueData(data model.AutoGenerated, configs config.DDLTransform, isFromSource bool) (Column, ColumnValue) {
	var column Column
	var columnValue ColumnValue
	var payloadAfter map[string]interface{}
	var payloadBefore map[string]interface{}
	dataType := map[string]string{}
	if isFromSource {
		for _, v := range configs.ModifyDataType {
			dataType[v.Column] = v.NewType
		}
	} else {
		for _, v := range configs.ModifyDataType {
			dataType[v.Column] = v.OldType
		}
	}
	if value, ok := data.Payload.After.(map[string]interface{}); ok {
		payloadAfter = value
	}
	if value, ok := data.Payload.Before.(map[string]interface{}); ok {
		payloadBefore = value
	}
	// if data.Payload.Op == "c" || data.Payload.Op == "u" || data.Payload.Op == "r" {
	// 	payloadAfter = data.Payload.After.(map[string]interface{})

	// }
	// if data.Payload.Op == "d" || data.Payload.Op == "u" {
	// 	payloadBefore = data.Payload.Before.(map[string]interface{})
	// }
	for key, val := range payloadAfter {
		column.After = append(column.After, key)
		if val == nil {
			columnValue.After = append(columnValue.After, "NULL")
		} else {
			var columnValueTemp string
			if reflect.ValueOf(val).Kind() == reflect.String {
				columnValueTemp = fmt.Sprintf("'%v'", val)
			} else if ok, temporalType := DetectTemporalType(data, key); ok {
				columnValueTemp = ConvertTemporalOnInsert(temporalType, val)
			} else {
				columnValueTemp = fmt.Sprintf("%v", val)
			}
			if newType, ok := dataType[key]; ok {
				columnValueTemp += "::" + newType
			}
			columnValue.After = append(columnValue.After, columnValueTemp)
		}
	}
	for key, val := range payloadBefore {
		column.Before = append(column.Before, key)
		if val == nil {
			columnValue.Before = append(columnValue.Before, "NULL")
		} else {
			var columnValueTemp string
			if reflect.ValueOf(val).Kind() == reflect.String {
				columnValueTemp = fmt.Sprintf("'%v'", val)
			} else if ok, temporalType := DetectTemporalType(data, key); ok {
				columnValueTemp = ConvertTemporalOnInsert(temporalType, val)
			} else {
				columnValueTemp = fmt.Sprintf("%v", val)
			}
			if newType, ok := dataType[key]; ok {
				columnValueTemp += "::" + newType
			}
			columnValue.Before = append(columnValue.Before, columnValueTemp)
		}
	}
	return column, columnValue

}
func ConvertDataToSQLVerticalSplittingDest(data model.AutoGenerated, configs config.DDLTransform) string {
	var Query string
	var primaryKey string
	// sourceTable := configs.CreateTable[0].RelatedTable
	primaryKeyList := configs.CreateTable[0].RelatedTablePrimaryKeys
	primaryKeyValue := []string{}
	column, columnValue := ExtractColumnAndValueData(data, configs, false)
	var selectedColumn, selectedColumnValue []string
	if data.Payload.Op == "c" || data.Payload.Op == "r" {
		selectedColumn = column.After
		selectedColumnValue = columnValue.After
	}
	if data.Payload.Op == "d" || data.Payload.Op == "u" {
		selectedColumn = column.Before
		selectedColumnValue = columnValue.Before
	}
	columnMap := map[string]string{}
	for i, v := range selectedColumn {
		columnMap[v] = selectedColumnValue[i]
	}
	for _, v := range primaryKeyList {
		primaryKeyValue = append(primaryKeyValue, v+"="+columnMap[v])
	}
	primaryKey = strings.Join(primaryKeyValue, " AND ")
	destTable := configs.CreateTable[0].RelatedTable
	if data.Payload.Op == "c" || data.Payload.Op == "r" {
		//Insert if not exists
		insertColumn := strings.Join(column.After, ",")
		insertColumnValue := strings.Join(columnValue.After, ",")
		Query += fmt.Sprintf("INSERT INTO %s (%s) SELECT %s WHERE NOT EXISTS (SELECT * FROM %s WHERE %s);", destTable, insertColumn, insertColumnValue, destTable, primaryKey)
	}
	var updateStatement string
	if data.Payload.Op == "u" || data.Payload.Op == "c" || data.Payload.Op == "r" {
		updateStatement = fmt.Sprintf("UPDATE %s set ", destTable)
		for i, col := range column.After {
			updateStatement += fmt.Sprintf("%s=%s,", col, columnValue.After[i])
		}
	}
	if data.Payload.Op == "d" {
		updateStatement = fmt.Sprintf("UPDATE %s set ", destTable)
		column, columnValue = RemovePrimaryKeyFromColumnAndColumnValue(column, columnValue, primaryKeyList)
		for _, col := range column.Before {
			updateStatement += fmt.Sprintf("%s ISNULL,", col)
			// updateStatement += fmt.Sprintf("%s=%s,", col, "NULL")
		}
	}
	updateStatement = strings.TrimSuffix(updateStatement, ",")
	Query += updateStatement + fmt.Sprintf(" WHERE %s;", primaryKey)

	return Query
	// return ConvertDataToSQLDenormalize(data, configs, false, primaryKey)
	// }

}

func ConvertDataToSQL(data model.AutoGenerated, primaryKey map[string][]string, configs config.DDLTransform, isFromSource bool, db *sql.DB) string {
	var Query string
	if len(configs.VerticalSplitting) > 0 && isFromSource {
		Query = ConvertDataToSQLVerticalSplitting(data, primaryKey, configs, db)
		// log.Println("Option ", 1)
	} else if len(configs.CreateTable) > 0 && configs.CreateTable[0].BeingUsed && !isFromSource {
		Query = ConvertDataToSQLVerticalSplittingDest(data, configs)
		// log.Println("Option ", 2)
	} else {
		Query = ConvertDataToSQLNormal(data, primaryKey, configs, isFromSource, db)
		// log.Println("Option ", 3)
	}
	return Query
}
