package services

import (
	"context"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"log"
	"strconv"
	"time"

	"github.com/go-redis/redis/v8"
	"github.com/lib/pq"
	"github.com/rweebs/cdc-bowo/internal/app/config"
	"github.com/rweebs/cdc-bowo/internal/app/lib"
	"github.com/rweebs/cdc-bowo/internal/app/model"
	"github.com/rweebs/cdc-bowo/internal/app/types"
	"github.com/rweebs/cdc-bowo/internal/app/utils"
)

type CDCSourceServices struct {
	dbSource           lib.Database
	dbDest             lib.Database
	rdb                lib.Cache
	primaryKeyList     map[string][]string
	RedisStreamList    map[string]string
	transformationList map[string]config.DDLTransform
	config             config.Config
}

func (s *CDCSourceServices) ExecuteDDLChange() {
	_, err := s.rdb.Cache.Get(context.Background(), "execute-ddl-change").Result()
	if err == nil {
		log.Println("DDL ALready Executed. Skipping DDL Execution")
	} else {
		log.Println("Execute DDL Change")
		sqlFile, err := ioutil.ReadFile(s.config.SQLFile)
		if err != nil {
			log.Println(err)
		}
		sql := string(sqlFile)
		_, err = utils.SQLExecutor(s.dbDest.Db, sql)
		if err != nil {
			log.Println(err)
			panic("Error Execute DDL Change")
		}
		s.rdb.Cache.Set(context.Background(), "execute-ddl-changet", 1, 0)
		log.Println("Execute DDL Change Done")
	}

	// statements := strings.Split(sql, ";")
	// for _, statement := range statements {
	// 	_, err = utils.SQLExecutor(s.dbDest.Db, statement)
	// 	if err != nil {
	// 		log.Println(err)
	// 	}
	// }

}
func (s *CDCSourceServices) StartService(startTimestamp int64) {
	mainContext := context.Background()
	failedStatement := types.NewFIFOMap()
Loop:
	for {
		val, _ := s.GetTimeStampCutOff()
		// log.Println(val)

		// for {

		var ctx context.Context
		// val, _ := s.getTimeStampCutOff()
		// if val > 0 {
		ctx, _ = context.WithTimeout(mainContext, 2*time.Second)
		// defer cancel()
		// } else {
		// ctx = mainContext
		// }
		// log.Println(ctx)
		entries, err := s.rdb.Cache.XRead(ctx, &redis.XReadArgs{

			Streams: makeStream(s.RedisStreamList),
			Count:   100,
			Block:   0,
		}).Result()
		if err != nil {
			// log.Println(err)
			// continue
		}
		if val > 0 && len(entries) == 0 {

			break Loop
		}
		// if len(entries) == 0 {
		// 	break Loop
		// }
		for _, streamEntries := range entries {
			for _, entry := range streamEntries.Messages {

				log.Println("Received event from stream", streamEntries.Stream)
				for _, v := range entry.Values {
					// log.Println(v)
					var sql string
					var dat model.AutoGenerated
					if err := json.Unmarshal([]byte(fmt.Sprintf("%v", v)), &dat); err != nil {
						continue
					}
					// if timeCutOff, err := s.getTimeStampCutOff(); err == nil && dat.Payload.TsMs > timeCutOff {
					// 	break Loop
					// }
					// if dat.Payload.Op == "u" {
					// 	data, _ := json.MarshalIndent(dat, "", "  ")
					// 	// Print json formatted
					// 	// log.Println(key)
					// 	log.Println(string(data))
					// }
					// // log.Println(val)
					// log.Println("timestamp now", time.Now().UnixMilli())
					// log.Println("timestamp data", dat.Payload.TsMs)
					// log.Println("Timestamp", "'%s'", time.Unix(0, int64(dat.Payload.TsMs)*1000000).UTC().Format(time.RFC3339Nano))
					// log.Println("Created At", "'%s'", dat.Payload.After.(map[string]interface{})["created_at"])
					if dat.Payload.TsMs < startTimestamp {

						continue
					}
					if val, ok := s.transformationList[fmt.Sprintf("%s.%s", dat.Payload.Source.Schema, dat.Payload.Source.Table)]; ok {
						dat = utils.ConvertSchema(dat, val)

						sql = utils.ConvertDataToSQL(dat, s.primaryKeyList, val, true, s.dbSource.Db)
					} else {
						sql = utils.ConvertDataToSQL(dat, s.primaryKeyList, config.DDLTransform{}, true, s.dbSource.Db)
					}

					_, err := utils.SQLExecutor(s.dbDest.Db, sql)
					if err != nil {
						// log.Println(err)
						if err.(*pq.Error).Code == "23503" {
							failedStatement.Set(entry.ID, sql)
						}
					}
					failedStatementKeys := failedStatement.Keys()
					for _, key := range failedStatementKeys {
						if sql, ok := failedStatement.Get(key); ok {
							_, err := utils.SQLExecutor(s.dbDest.Db, sql.(string))
							if err != nil {
								log.Println(err)
							} else {
								failedStatement.Delete(key)
							}
						}
					}

					// log.Println(result2, err)
				}
				s.RedisStreamList[streamEntries.Stream] = entry.ID
			}
		}

	}
	// }
}

func (s *CDCSourceServices) StopService() {
	data, _ := json.Marshal(s.RedisStreamList)
	s.rdb.Cache.Set(context.Background(), "sourceRedisStreamList", data, 0)
	log.Println("Stop Source Service")
}

func (s *CDCSourceServices) GetTimeStampCutOff() (int64, error) {
	res, err := s.rdb.Cache.Get(context.Background(), "cdc-source-stop-timestamp").Result()
	if err != nil {
		return 0, err
	}
	result, err := strconv.ParseInt(res, 10, 64)
	return result, err
}

func NewCDCSourceServices(dbSource lib.Database, dbDest lib.Database, rdb lib.Cache, config config.Config) *CDCSourceServices {
	sqlFile, err := ioutil.ReadFile(config.SQLFile)
	if err != nil {
		panic(`Error reading SQL file`)
	}
	return &CDCSourceServices{
		dbSource:           dbSource,
		dbDest:             dbDest,
		rdb:                rdb,
		primaryKeyList:     initPrimaryKeyList(dbSource.Db),
		RedisStreamList:    initRedisStreamList(dbSource.Db, rdb.Cache, "sourceRedisStreamList", config.SourceConfig.DebeziumPublication, config.SourceConfig.RedisTopicPrefix),
		config:             config,
		transformationList: utils.InitTransformListNew(string(sqlFile), config.DDLTransform),
	}
}

func (s *CDCSourceServices) checkReplicationCatchUp() (bool, error) {
	var different_lsn int64
	err := s.dbSource.Db.QueryRow("SELECT pg_current_wal_lsn()-replay_lsn FROM pg_stat_replication where application_name=$1;", s.config.DestConfig.SubscriptionName).Scan(&different_lsn)
	if err != nil {
		return true, nil
	}

	return different_lsn < 100, nil
}

func (s *CDCSourceServices) dropDestSubscription() error {
	_, err := s.dbDest.Db.Exec("DROP SUBSCRIPTION IF EXISTS " + s.config.DestConfig.SubscriptionName + ";")
	return err
}

func (s *CDCSourceServices) checkStopReplicationReady() bool {
	res, err := s.rdb.Cache.Get(context.Background(), "stop-replication-ready").Result()
	if err != nil {
		return false
	}
	result, err := strconv.ParseInt(res, 10, 64)
	if err != nil {
		return false
	}
	log.Println(result)
	return result == 1
}

func (s *CDCSourceServices) StopReplication() (int64, error) {
	for !s.checkStopReplicationReady() {
		log.Println("Waiting to start application")
		time.Sleep(100 * time.Millisecond)
	}
	log.Println("Proceed to stop replication waiting for replication catch up")
	for result, err := s.checkReplicationCatchUp(); err != nil || !result; result, err = s.checkReplicationCatchUp() {
		time.Sleep(100 * time.Millisecond)
		log.Println("Waiting for replication catch up")
	}
	log.Println("Replication catch up, start to drop subscription")
	timestamp := time.Now().UnixNano() / int64(time.Millisecond)
	s.rdb.Cache.Set(context.Background(), "stop-replication-timestamp", timestamp, 0)
	err := s.dropDestSubscription()

	return timestamp, err
}
