package services

import (
	"context"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"log"
	"strconv"
	"time"

	"github.com/go-redis/redis/v8"
	"github.com/lib/pq"
	"github.com/rweebs/cdc-bowo/internal/app/config"
	"github.com/rweebs/cdc-bowo/internal/app/lib"
	"github.com/rweebs/cdc-bowo/internal/app/model"
	"github.com/rweebs/cdc-bowo/internal/app/types"
	"github.com/rweebs/cdc-bowo/internal/app/utils"
)

type CDCSourceServices struct {
	dbSource           lib.Database
	dbDest             lib.Database
	rdb                lib.Cache
	primaryKeyList     map[string][]string
	RedisStreamList    map[string]string
	transformationList map[string]config.DDLTransform
	config             config.Config
}

>>>>>>>>>>DOCIFY-START - qvuujexhjgrh >>>>>>>>>>
// Execute DDL Change Executes the sql file and updates the db destionation to match the schema of
// 
// Args:
// 	 s
>>>>>>>>>>DOCIFY-END - qvuujexhjgrh >>>>>>>>>>
func (s *CDCSourceServices) ExecuteDDLChange() {
	_, err := s.rdb.Cache.Get(context.Background(), "execute-ddl-change").Result()
>>>>>>>>>>DOCIFY-START - ccqwujscwdim >>>>>>>>>>
	// Execute DDL Change DDL Change
>>>>>>>>>>DOCIFY-END - ccqwujscwdim >>>>>>>>>>
	if err == nil {
		log.Println("DDL ALready Executed. Skipping DDL Execution")
	} else {
		log.Println("Execute DDL Change")
		sqlFile, err := ioutil.ReadFile(s.config.SQLFile)
>>>>>>>>>>DOCIFY-START - rycqravctysm >>>>>>>>>>
		// Print out the error message.
>>>>>>>>>>DOCIFY-END - rycqravctysm >>>>>>>>>>
		if err != nil {
			log.Println(err)
		}
		sql := string(sqlFile)
		_, err = utils.SQLExecutor(s.dbDest.Db, sql)
>>>>>>>>>>DOCIFY-START - sjsdtqelsbyy >>>>>>>>>>
		// Execute DDL Change. Panic on error.
>>>>>>>>>>DOCIFY-END - sjsdtqelsbyy >>>>>>>>>>
		if err != nil {
			log.Println(err)
			log.Panic("Error Execute DDL Change")
		}
		s.rdb.Cache.Set(context.Background(), "execute-ddl-change", 1, 0)
		log.Println("Execute DDL Change Done")
	}

	// statements := strings.Split(sql, ";")
	// for _, statement := range statements {
	// 	_, err = utils.SQLExecutor(s.dbDest.Db, statement)
	// 	if err != nil {
	// 		log.Println(err)
	// 	}
	// }

}
>>>>>>>>>>DOCIFY-START - yiuqblemszpm >>>>>>>>>>
// StartService starts CDCSourceServices in a loop. The loop is terminated when there are no events to process.
// 
// Args:
// 	 s: The instance of CDCSourceServices to start.
// 	 startTimestamp: The timestamp at which to start the service
>>>>>>>>>>DOCIFY-END - yiuqblemszpm >>>>>>>>>>
func (s *CDCSourceServices) StartService(startTimestamp int64) {
	mainContext := context.Background()
	failedStatement := types.NewFIFOMap()
Loop:
>>>>>>>>>>DOCIFY-START - wdadavelpcnf >>>>>>>>>>
	// Loop through all the records in the cache and return them.
>>>>>>>>>>DOCIFY-END - wdadavelpcnf >>>>>>>>>>
	for {
		val, _ := s.GetTimeStampCutOff()
		// log.Println(val)

		// for {

		var ctx context.Context
		// val, _ := s.getTimeStampCutOff()
		// if val > 0 {
		ctx, _ = context.WithTimeout(mainContext, 2*time.Second)
		// defer cancel()
		// } else {
		// ctx = mainContext
		// }
		// log.Println(ctx)
		entries, err := s.rdb.Cache.XRead(ctx, &redis.XReadArgs{

			Streams: makeStream(s.RedisStreamList),
			Count:   1000,
			Block:   0,
		}).Result()
>>>>>>>>>>DOCIFY-START - auvpojbqhtqe >>>>>>>>>>
		// if err is not nil print out the error message
>>>>>>>>>>DOCIFY-END - auvpojbqhtqe >>>>>>>>>>
		if err != nil {
			// log.Println(err)
			// continue
		}
>>>>>>>>>>DOCIFY-START - xtndhanprkdv >>>>>>>>>>
		// Loop Loop Loop if val 0
>>>>>>>>>>DOCIFY-END - xtndhanprkdv >>>>>>>>>>
		if val > 0 && len(entries) == 0 {

			break Loop
		}
		// if len(entries) == 0 {
		// 	break Loop
		// }
		// This function is used to parse the stream entries from the stream entries.
		for _, streamEntries := range entries {
			// This function is used to parse streamEntries. Messages and send them to the database.
			for _, entry := range streamEntries.Messages {

				log.Println("Received event from stream", streamEntries.Stream)
				// Print all the data in the entry. Values
				for _, v := range entry.Values {
					// log.Println(v)
					var sql string
					var dat model.AutoGenerated
					// Unmarshal the json string v and return the data
					if err := json.Unmarshal([]byte(fmt.Sprintf("%v", v)), &dat); err != nil {
						continue
					}
					// if timeCutOff, err := s.getTimeStampCutOff(); err == nil && dat.Payload.TsMs > timeCutOff {
					// 	break Loop
					// }
					// if dat.Payload.Op == "u" {
					// 	data, _ := json.MarshalIndent(dat, "", "  ")
					// 	// Print json formatted
					// 	// log.Println(key)
					// 	log.Println(string(data))
					// }
					// // log.Println(val)
					// log.Println("timestamp now", time.Now().UnixMilli())
					// log.Println("timestamp data", dat.Payload.TsMs)
					// log.Println("Timestamp", "'%s'", time.Unix(0, int64(dat.Payload.TsMs)*1000000).UTC().Format(time.RFC3339Nano))
					// log.Println("Created At", "'%s'", dat.Payload.After.(map[string]interface{})["created_at"])
					// If the startTimestamp is less than startTimestamp then continue to start the process.
					if dat.Payload.TsMs < startTimestamp {

						continue
					}
					// Convert schema and table to SQL.
					if val, ok := s.transformationList[fmt.Sprintf("%s.%s", dat.Payload.Source.Schema, dat.Payload.Source.Table)]; ok {
						dat = utils.ConvertSchema(dat, val)

						sql = utils.ConvertDataToSQL(dat, s.primaryKeyList, val, true, s.dbSource.Db)
					} else {
						sql = utils.ConvertDataToSQL(dat, s.primaryKeyList, config.DDLTransform{}, true, s.dbSource.Db)
					}

					_, err := utils.SQLExecutor(s.dbDest.Db, sql)
					// Set the failed statement to the failed statement
					if err != nil {
						// log.Println(err)
						// Set the failed statement to the failed statement.
						if err.(*pq.Error).Code == "23503" {
							failedStatement.Set(entry.ID, sql)
						}
					}
					failedStatementKeys := failedStatement.Keys()
					// Delete all failed statements from failedStatementKeys
					for _, key := range failedStatementKeys {
						// Delete failed statement by key.
						if sql, ok := failedStatement.Get(key); ok {
							_, err := utils.SQLExecutor(s.dbDest.Db, sql.(string))
							// Delete the failed statement.
							if err != nil {
								log.Println(err)
							} else {
								failedStatement.Delete(key)
							}
						}
					}

					// log.Println(result2, err)
				}
				s.RedisStreamList[streamEntries.Stream] = entry.ID
			}
		}

	}
	// }
}

// StopService stops the CDCSourceServices from accepting new streams and stores them in the cache. This is useful for debugging and testing purposes
// 
// Args:
// 	 s
func (s *CDCSourceServices) StopService() {
	data, _ := json.Marshal(s.RedisStreamList)
	s.rdb.Cache.Set(context.Background(), "sourceRedisStreamList", data, 0)
	log.Println("Stop Source Service")
}

// GetTimeStampCutOff returns the timestamp cut off in nanoseconds. This is used to determine when to stop
// 
// Args:
// 	 s
func (s *CDCSourceServices) GetTimeStampCutOff() (int64, error) {
	res, err := s.rdb.Cache.Get(context.Background(), "cdc-source-stop-timestamp").Result()
	// Returns 0 err if any error occurs.
	if err != nil {
		return 0, err
	}
	result, err := strconv.ParseInt(res, 10, 64)
	return result, err
}

// NewCDCSourceServices creates a new instance of CDCSourceServices. Note that you must call Close on the returned instance to release resources
// 
// Args:
// 	 dbSource: database to read from.
// 	 dbDest: database to write to. It is up to the caller to make sure the destination is closed before returning to the caller.
// 	 rdb: Redis instance to use for Redis streams.
// 	 config: Configuration for the source and destination databases. See config. SourceConfig
func NewCDCSourceServices(dbSource lib.Database, dbDest lib.Database, rdb lib.Cache, config config.Config) *CDCSourceServices {
	sqlFile, err := ioutil.ReadFile(config.SQLFile)
	// Read the SQL file and log error
	if err != nil {
		log.Panic(`Error reading SQL file`)
	}
	return &CDCSourceServices{
		dbSource:           dbSource,
		dbDest:             dbDest,
		rdb:                rdb,
		primaryKeyList:     initPrimaryKeyList(dbSource.Db),
		RedisStreamList:    initRedisStreamList(dbSource.Db, rdb.Cache, "sourceRedisStreamList", config.SourceConfig.DebeziumPublication, config.SourceConfig.RedisTopicPrefix),
		config:             config,
		transformationList: utils.InitTransformListNew(string(sqlFile), config.DDLTransform),
	}
}

// Checks if replication should be catch up. It is used to detect if we have to recover from replication errors that are due to some part of the cluster being down and if so we need to re check the replication count in pg_stat_replication for a short period of time.
// 
// Args:
// 	 s: CDCSourceServices for the source we are
func (s *CDCSourceServices) checkReplicationCatchUp() (bool, error) {
	var different_lsn int64
	err := s.dbSource.Db.QueryRow("SELECT pg_current_wal_lsn()-replay_lsn FROM pg_stat_replication where application_name=$1;", s.config.DestConfig.SubscriptionName).Scan(&different_lsn)
	// If an error occurs during the test.
	if err != nil {
		return true, nil
	}

	return different_lsn < 100, nil
}

// dropDestSubscription drops the subscription for the destination CDC. This is used to ensure that the subscription is no longer in use by any of the source services that are being moved to the destination.
// 
// Args:
// 	 s: the instance of CDCSourceServices. It must be locked before calling this method.
// 
// Returns: 
// 	 an error if the operation failed or was not successful. If the operation succeeded the error will be non nil
func (s *CDCSourceServices) dropDestSubscription() error {
	_, err := s.dbDest.Db.Exec("DROP SUBSCRIPTION IF EXISTS " + s.config.DestConfig.SubscriptionName + ";")
	return err
}

// checkStopReplicationReady checks if stop replication is ready. This is a hack to avoid running in production mode
// 
// Args:
// 	 s
// 
// Returns: 
// 	 true if ready false
func (s *CDCSourceServices) checkStopReplicationReady() bool {
	res, err := s.rdb.Cache.Get(context.Background(), "stop-replication-ready").Result()
	// Return false if an error occurs.
	if err != nil {
		return false
	}
	result, err := strconv.ParseInt(res, 10, 64)
	// Return false if an error occurs.
	if err != nil {
		return false
	}
	log.Println(result)
	return result == 1
}

// StopReplication check if replication catch up and if it is stop replication. It is called by source services when stop replication
// 
// Args:
// 	 s
func (s *CDCSourceServices) StopReplication() (int64, error) {
	// Wait for the application to stop replication
	for !s.checkStopReplicationReady() {
		log.Println("Waiting to start application")
		time.Sleep(100 * time.Millisecond)
	}
	log.Println("Proceed to stop replication waiting for replication catch up")
	// Check if the replication catch up.
	for result, err := s.checkReplicationCatchUp(); err != nil || !result; result, err = s.checkReplicationCatchUp() {
		time.Sleep(100 * time.Millisecond)
		log.Println("Waiting for replication catch up")
	}
	log.Println("Replication catch up, start to drop subscription")
	timestamp := time.Now().UnixNano() / int64(time.Millisecond)
	s.rdb.Cache.Set(context.Background(), "stop-replication-timestamp", timestamp, 0)
	err := s.dropDestSubscription()

	return timestamp, err
}
