package services

import (
	"context"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"log"
	"time"

	"github.com/go-redis/redis/v8"
	"github.com/lib/pq"
	"github.com/rweebs/cdc-bowo/internal/app/config"
	"github.com/rweebs/cdc-bowo/internal/app/lib"
	"github.com/rweebs/cdc-bowo/internal/app/model"
	"github.com/rweebs/cdc-bowo/internal/app/types"
	"github.com/rweebs/cdc-bowo/internal/app/utils"
)

type CDCDestServices struct {
	dbSource           lib.Database
	dbDest             lib.Database
	rdb                lib.Cache
	primaryKeyList     map[string][]string
	redisStreamList    map[string]string
	timeStampCutOff    int64
	transformationList map[string]config.DDLTransform
	config             config.Config
}

func (s *CDCDestServices) StartService(startTimestamp int64) {
	// Loop:
	failedStatement := types.NewFIFOMap()
	for {

		entries, err := s.rdb.Cache.XRead(context.Background(), &redis.XReadArgs{

			Streams: makeStream(s.redisStreamList),
			Count:   1000,
			Block:   0,
		}).Result()
		if err != nil {
			log.Println(err)
			// continue
		}

		for _, streamEntries := range entries {
			for _, entry := range streamEntries.Messages {

				log.Println("Received event from stream", streamEntries.Stream)
				for _, v := range entry.Values {
					var sql string
					var dat model.AutoGenerated
					if err := json.Unmarshal([]byte(fmt.Sprintf("%v", v)), &dat); err != nil {
						log.Println(err)
					}
					// data, _ := json.MarshalIndent(dat, "", "  ")
					// // Print json formatted
					// log.Println(string(data))
					if dat.Payload.TsMs < startTimestamp {
						continue
					}

					if val, ok := s.transformationList[fmt.Sprintf("%s.%s", dat.Payload.Source.Schema, dat.Payload.Source.Table)]; ok {
						dat = utils.ConvertSchemaDest(dat, val)

						sql = utils.ConvertDataToSQL(dat, s.primaryKeyList, val, false, s.dbSource.Db)
					} else {
						sql = utils.ConvertDataToSQL(dat, s.primaryKeyList, config.DDLTransform{}, false, s.dbSource.Db)
					}
					_, err := utils.SQLExecutor(s.dbSource.Db, sql)
					if err != nil {
						// log.Println(err)
						if err.(*pq.Error).Code == "23503" {
							failedStatement.Set(entry.ID, sql)
						}
					}
					failedStatementKeys := failedStatement.Keys()
					for _, key := range failedStatementKeys {
						if sql, ok := failedStatement.Get(key); ok {
							_, err := utils.SQLExecutor(s.dbDest.Db, sql.(string))
							if err != nil {
								log.Println(err)
							} else {
								failedStatement.Delete(key)
							}
						}
					}
					// log.Println(utils.ConvertDataToSQL(dat, s.primaryKeyList, config.DDLTransform{}))
				}
				s.redisStreamList[streamEntries.Stream] = entry.ID
			}
		}
	}
}

// TODO:
func (s *CDCDestServices) StopService() {
	data, _ := json.Marshal(s.redisStreamList)
	s.rdb.Cache.Set(context.Background(), "destRedisStreamList", data, 0)
	log.Println("Stop Dest Service")

}
func NewCDCDestServices(dbSource lib.Database, dbDest lib.Database, rdb lib.Cache, config config.Config) *CDCDestServices {
	sqlFile, err := ioutil.ReadFile(config.SQLFile)
	if err != nil {
		log.Panic(`Error reading SQL file`)
	}
	return &CDCDestServices{
		dbSource:           dbSource,
		dbDest:             dbDest,
		rdb:                rdb,
		primaryKeyList:     initPrimaryKeyList(dbSource.Db),
		redisStreamList:    initRedisStreamList(dbSource.Db, rdb.Cache, "destRedisStreamList", config.DestConfig.DebeziumPublication, config.DestConfig.RedisTopicPrefix),
		timeStampCutOff:    time.Now().UnixNano() / int64(time.Millisecond),
		config:             config,
		transformationList: utils.InitTransformListDestNew(string(sqlFile), config.DDLTransform),
	}
}

// func initTransformListDest(configs config.DDLTransform) map[string]config.DDLTransform {
// 	transformList := map[string]config.DDLTransform{}
// 	//AddColumn become drop column
// 	for _, v := range configs.AddColumn {
// 		schemaTable := fmt.Sprintf("%s.%s", v.Schema, v.Table)
// 		object := transformList[schemaTable]
// 		object.AddColumn = append(object.AddColumn, v)
// 		transformList[schemaTable] = object
// 	}
// 	//DONE:
// 	for _, v := range configs.DropColumn {
// 		schemaTable := fmt.Sprintf("%s.%s", v.Schema, v.Table)
// 		object := transformList[schemaTable]
// 		object.DropColumn = append(object.DropColumn, v)
// 		transformList[schemaTable] = object
// 	}
// 	//TODO:
// 	for _, v := range configs.DropNotNullConstraint {
// 		schemaTable := fmt.Sprintf("%s.%s", v.Schema, v.Table)
// 		object := transformList[schemaTable]
// 		object.DropNotNullConstraint = append(object.DropNotNullConstraint, v)
// 		transformList[schemaTable] = object
// 	}
// 	//TODO:
// 	for _, v := range configs.ModifyDataType {
// 		schemaTable := fmt.Sprintf("%s.%s", v.Schema, v.Table)
// 		object := transformList[schemaTable]
// 		object.ModifyDataType = append(object.ModifyDataType, v)
// 		transformList[schemaTable] = object
// 	}
// 	//DONE:
// 	for _, v := range configs.RenameColumn {
// 		schemaTable := fmt.Sprintf("%s.%s", v.Schema, v.Table)
// 		object := transformList[schemaTable]
// 		object.RenameColumn = append(object.RenameColumn, v)
// 		transformList[schemaTable] = object
// 	}
// 	//DONE:
// 	for _, v := range configs.RenameTable {
// 		schemaTable := fmt.Sprintf("%s.%s", v.Schema, v.NewName)
// 		object := transformList[schemaTable]
// 		object.RenameTable = append(object.RenameTable, v)
// 		transformList[schemaTable] = object
// 	}

// 	return transformList
// }
