package services

import (
	"context"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"log"
	"time"

	"github.com/go-redis/redis/v8"
	"github.com/lib/pq"
	"github.com/rweebs/cdc-bowo/internal/app/config"
	"github.com/rweebs/cdc-bowo/internal/app/lib"
	"github.com/rweebs/cdc-bowo/internal/app/model"
	"github.com/rweebs/cdc-bowo/internal/app/types"
	"github.com/rweebs/cdc-bowo/internal/app/utils"
)

type CDCDestServices struct {
	dbSource           lib.Database
	dbDest             lib.Database
	rdb                lib.Cache
	primaryKeyList     map[string][]string
	redisStreamList    map[string]string
	timeStampCutOff    int64
	transformationList map[string]config.DDLTransform
	config             config.Config
}

// StartService starts the CDCDestServices. This is the main loop of the service. It reads events from Redis and sends them to the destination database
//
// Args:
//
//	s: The instance of the service
//	startTimestamp: The timestamp at which to start the service
func (s *CDCDestServices) StartService(startTimestamp int64) {
	// Loop:
	failedStatement := types.NewFIFOMap()
	// This function is used to read all the events from redis.
	for {

		entries, err := s.rdb.Cache.XRead(context.Background(), &redis.XReadArgs{

			Streams: makeStream(s.redisStreamList),
			Count:   1000,
			Block:   0,
		}).Result()
		// Print out any error messages.
		if err != nil {
			log.Println(err)
			// continue
		}

		// This function will be called when a stream is received from the server.
		for _, streamEntries := range entries {
			// This function is used to handle incoming stream entries
			for _, entry := range streamEntries.Messages {

				log.Println("Received event from stream", streamEntries.Stream)
				// Print all the values in the entry. Values
				for _, v := range entry.Values {
					var sql string
					var dat model.AutoGenerated
					// Unmarshal json string to a dat object
					if err := json.Unmarshal([]byte(fmt.Sprintf("%v", v)), &dat); err != nil {
						log.Println(err)
					}
					// data, _ := json.MarshalIndent(dat, "", "  ")
					// // Print json formatted
					// log.Println(string(data))
					//buffer 200 ms
					// If dat. Payload. TsMs is less than startTimestamp 200 milliseconds.
					if dat.Payload.TsMs < startTimestamp-(200*time.Millisecond).Microseconds() {
						continue
					}

					// Convert schema and table to SQL.
					if val, ok := s.transformationList[fmt.Sprintf("%s.%s", dat.Payload.Source.Schema, dat.Payload.Source.Table)]; ok {
						dat = utils.ConvertSchemaDest(dat, val)

						sql = utils.ConvertDataToSQL(dat, s.primaryKeyList, val, false, s.dbSource.Db)
					} else {
						sql = utils.ConvertDataToSQL(dat, s.primaryKeyList, config.DDLTransform{}, false, s.dbSource.Db)
					}
					_, err := utils.SQLExecutor(s.dbSource.Db, sql)
					// Set the failed statement to the failed statement
					if err != nil {
						// log.Println(err)
						// Set the failed statement to the failed statement.
						if err.(*pq.Error).Code == "23503" {
							failedStatement.Set(entry.ID, sql)
						}
					}
					failedStatementKeys := failedStatement.Keys()
					// Delete all failed statements from failedStatementKeys
					for _, key := range failedStatementKeys {
						// Delete failed statement by key.
						if sql, ok := failedStatement.Get(key); ok {
							_, err := utils.SQLExecutor(s.dbDest.Db, sql.(string))
							// Delete the failed statement.
							if err != nil {
								log.Println(err)
							} else {
								failedStatement.Delete(key)
							}
						}
					}
					// log.Println(utils.ConvertDataToSQL(dat, s.primaryKeyList, config.DDLTransform{}))
				}
				s.redisStreamList[streamEntries.Stream] = entry.ID
			}
		}
	}
}

// TODO:
// StopService stops dest service and stores it in cache. It is called when service is stopped and can be used to clean up
//
// Args:
//
//	s
func (s *CDCDestServices) StopService() {
	data, _ := json.Marshal(s.redisStreamList)
	s.rdb.Cache.Set(context.Background(), "destRedisStreamList", data, 0)
	log.Println("Stop Dest Service")

}

// NewCDCDestServices creates a new instance of CDCDestServices. Note that this is a factory method and should not be called externally
//
// Args:
//
//	dbSource: database to read from.
//	dbDest: database to write to. It is used as destination for data transfer
//	rdb: Redis instance to use for data transfer
//	config: Configuration for the destination services. See config.
func NewCDCDestServices(dbSource lib.Database, dbDest lib.Database, rdb lib.Cache, config config.Config) *CDCDestServices {
	sqlFile, err := ioutil.ReadFile(config.SQLFile)
	// Read the SQL file and log error
	if err != nil {
		log.Panic(`Error reading SQL file`)
	}
	return &CDCDestServices{
		dbSource:           dbSource,
		dbDest:             dbDest,
		rdb:                rdb,
		primaryKeyList:     initPrimaryKeyList(dbSource.Db),
		redisStreamList:    initRedisStreamList(dbSource.Db, rdb.Cache, "destRedisStreamList", config.DestConfig.DebeziumPublication, config.DestConfig.RedisTopicPrefix),
		timeStampCutOff:    time.Now().UnixNano() / int64(time.Millisecond),
		config:             config,
		transformationList: utils.InitTransformListDestNew(string(sqlFile), config.DDLTransform),
	}
}
