package services

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/go-redis/redis/v8"
	"github.com/rweebs/cdc-bowo/internal/app/config"
	"github.com/rweebs/cdc-bowo/internal/app/lib"
	"github.com/rweebs/cdc-bowo/internal/app/model"
	"github.com/rweebs/cdc-bowo/internal/app/utils"
)

type CDCDestServices struct {
	dbSource           lib.Database
	dbDest             lib.Database
	rdb                lib.Cache
	primaryKeyList     map[string][]string
	redisStreamList    map[string]string
	timeStampCutOff    int64
	transformationList map[string]config.DDLTransform
	config             config.Config
}

func (s *CDCDestServices) StartService() {
Loop:
	for {

		entries, err := s.rdb.Cache.XRead(context.Background(), &redis.XReadArgs{

			Streams: makeStream(s.redisStreamList),
			Count:   1,
			Block:   0,
		}).Result()
		if err != nil {
			fmt.Println(err)
			// continue
		}

		for _, streamEntries := range entries {
			for _, entry := range streamEntries.Messages {

				// fmt.Println("Received event from stream", streamEntries.Stream)
				for _, v := range entry.Values {

					var dat model.AutoGenerated
					if err := json.Unmarshal([]byte(fmt.Sprintf("%v", v)), &dat); err != nil {
						fmt.Println(err)
					}

					if dat.Payload.TsMs > s.timeStampCutOff {
						break Loop
					}
					// fmt.Println(utils.ConvertDataToSQL(dat, s.primaryKeyList, config.DDLTransform{}))
				}
				s.redisStreamList[streamEntries.Stream] = entry.ID
			}
		}
	}
}

// TODO:
func (s *CDCDestServices) StopService() {

}
func NewCDCDestServices(dbSource lib.Database, dbDest lib.Database, rdb lib.Cache, config config.Config) *CDCDestServices {
	return &CDCDestServices{
		dbSource:           dbSource,
		dbDest:             dbDest,
		rdb:                rdb,
		primaryKeyList:     initPrimaryKeyList(dbSource.Db),
		redisStreamList:    initRedisStreamList(dbSource.Db, rdb.Cache, "destRedisStreamList"),
		timeStampCutOff:    time.Now().UnixNano() / int64(time.Millisecond),
		config:             config,
		transformationList: utils.InitTransformList(config.DDLTransform),
	}
}

// func initTransformListDest(configs config.DDLTransform) map[string]config.DDLTransform {
// 	transformList := map[string]config.DDLTransform{}
// 	//AddColumn become drop column
// 	for _, v := range configs.AddColumn {
// 		schemaTable := fmt.Sprintf("%s.%s", v.Schema, v.Table)
// 		object := transformList[schemaTable]
// 		object.AddColumn = append(object.AddColumn, v)
// 		transformList[schemaTable] = object
// 	}
// 	//DONE:
// 	for _, v := range configs.DropColumn {
// 		schemaTable := fmt.Sprintf("%s.%s", v.Schema, v.Table)
// 		object := transformList[schemaTable]
// 		object.DropColumn = append(object.DropColumn, v)
// 		transformList[schemaTable] = object
// 	}
// 	//TODO:
// 	for _, v := range configs.DropNotNullConstraint {
// 		schemaTable := fmt.Sprintf("%s.%s", v.Schema, v.Table)
// 		object := transformList[schemaTable]
// 		object.DropNotNullConstraint = append(object.DropNotNullConstraint, v)
// 		transformList[schemaTable] = object
// 	}
// 	//TODO:
// 	for _, v := range configs.ModifyDataType {
// 		schemaTable := fmt.Sprintf("%s.%s", v.Schema, v.Table)
// 		object := transformList[schemaTable]
// 		object.ModifyDataType = append(object.ModifyDataType, v)
// 		transformList[schemaTable] = object
// 	}
// 	//DONE:
// 	for _, v := range configs.RenameColumn {
// 		schemaTable := fmt.Sprintf("%s.%s", v.Schema, v.Table)
// 		object := transformList[schemaTable]
// 		object.RenameColumn = append(object.RenameColumn, v)
// 		transformList[schemaTable] = object
// 	}
// 	//DONE:
// 	for _, v := range configs.RenameTable {
// 		schemaTable := fmt.Sprintf("%s.%s", v.Schema, v.NewName)
// 		object := transformList[schemaTable]
// 		object.RenameTable = append(object.RenameTable, v)
// 		transformList[schemaTable] = object
// 	}

// 	return transformList
// }
