package services

import (
	"context"
	"encoding/json"
	"fmt"
	"strconv"
	"time"

	"github.com/go-redis/redis/v8"
	"github.com/rweebs/cdc-bowo/internal/app/config"
	"github.com/rweebs/cdc-bowo/internal/app/lib"
	"github.com/rweebs/cdc-bowo/internal/app/model"
	"github.com/rweebs/cdc-bowo/internal/app/utils"
)

type CDCSourceServices struct {
	dbSource           lib.Database
	dbDest             lib.Database
	rdb                lib.Cache
	primaryKeyList     map[string][]string
	RedisStreamList    map[string]string
	transformationList map[string]config.DDLTransform
	config             config.Config
}

func (s *CDCSourceServices) ExecuteDDLChange() {
	utils.SQLExecutor(s.dbDest.Db, s.config.SQLScript)
}
func (s *CDCSourceServices) StartService(startTimestamp int64) {
	mainContext := context.Background()
	// Loop:
	for {
		val, _ := s.getTimeStampCutOff()
		if val > 0 {
			break
		}
		// for {

		var ctx context.Context
		// val, _ := s.getTimeStampCutOff()
		// if val > 0 {
		ctx, _ = context.WithTimeout(mainContext, 3*time.Second)
		// defer cancel()
		// } else {
		// ctx = mainContext
		// }
		// fmt.Println(ctx)
		entries, err := s.rdb.Cache.XRead(ctx, &redis.XReadArgs{

			Streams: makeStream(s.RedisStreamList),
			Count:   1000,
			Block:   0,
		}).Result()
		if err != nil {
			fmt.Println(err)
			// continue
		}
		// if len(entries) == 0 {
		// 	break Loop
		// }
		for _, streamEntries := range entries {
			for _, entry := range streamEntries.Messages {

				fmt.Println("Received event from stream", streamEntries.Stream)
				for _, v := range entry.Values {
					// fmt.Println(v)
					var sql string
					var dat model.AutoGenerated
					if err := json.Unmarshal([]byte(fmt.Sprintf("%v", v)), &dat); err != nil {
						continue
					}
					// if timeCutOff, err := s.getTimeStampCutOff(); err == nil && dat.Payload.TsMs > timeCutOff {
					// 	break Loop
					// }
					// data, _ := json.MarshalIndent(dat, "", "  ")
					// Print json formatted
					// fmt.Println(key)
					// fmt.Println(string(data))
					// // fmt.Println(val)
					// fmt.Println("timestamp now", time.Now().UnixMilli())
					// fmt.Println("timestamp data", dat.Payload.TsMs)
					if dat.Payload.TsMs < startTimestamp {
						continue
					}
					if val, ok := s.transformationList[fmt.Sprintf("%s.%s", dat.Payload.Source.Schema, dat.Payload.Source.Table)]; ok {
						dat = utils.ConvertSchema(dat, val)

						sql = utils.ConvertDataToSQL(dat, s.primaryKeyList, val, true)
					} else {
						sql = utils.ConvertDataToSQL(dat, s.primaryKeyList, config.DDLTransform{}, true)
					}
					_, err := utils.SQLExecutor(s.dbDest.Db, sql)
					if err != nil {
						fmt.Println(err)
					}

					// fmt.Println(result2, err)
				}
				s.RedisStreamList[streamEntries.Stream] = entry.ID
			}
		}
	}
	// }
}

func (s *CDCSourceServices) StopService() {
	data, _ := json.Marshal(s.RedisStreamList)
	s.rdb.Cache.Set(context.Background(), "sourceRedisStreamList", data, 0)
	fmt.Println("Stop Source Service")
}

func (s *CDCSourceServices) getTimeStampCutOff() (int64, error) {
	res, err := s.rdb.Cache.Get(context.Background(), "cdc-source-expired").Result()
	if err != nil {
		return 0, err
	}
	result, err := strconv.ParseInt(res, 10, 64)
	return result, err
}

func NewCDCSourceServices(dbSource lib.Database, dbDest lib.Database, rdb lib.Cache, config config.Config) *CDCSourceServices {
	return &CDCSourceServices{
		dbSource:           dbSource,
		dbDest:             dbDest,
		rdb:                rdb,
		primaryKeyList:     initPrimaryKeyList(dbSource.Db),
		RedisStreamList:    initRedisStreamList(dbSource.Db, rdb.Cache, "sourceRedisStreamList"),
		config:             config,
		transformationList: utils.InitTransformList(config.DDLTransform),
	}
}

func (s *CDCSourceServices) checkReplicationCatchUp() (bool, error) {
	var different_lsn int64
	err := s.dbSource.Db.QueryRow("SELECT pg_current_wal_lsn()-replay_lsn FROM pg_stat_replication where application_name=$1;", s.config.DestConfig.SubscriptionName).Scan(&different_lsn)
	if err != nil {
		return true, nil
	}

	return different_lsn < 100, nil
}

func (s *CDCSourceServices) dropDestSubscription() error {
	_, err := s.dbDest.Db.Exec("DROP SUBSCRIPTION IF EXISTS " + s.config.DestConfig.SubscriptionName + ";")
	return err
}

func (s *CDCSourceServices) checkStopReplicationReady() bool {
	res, err := s.rdb.Cache.Get(context.Background(), "stop-replication-ready").Result()
	if err != nil {
		return false
	}
	result, err := strconv.ParseInt(res, 10, 64)
	if err != nil {
		return false
	}
	fmt.Println(result)
	return result == 1
}

func (s *CDCSourceServices) StopReplication() (int64, error) {
	for !s.checkStopReplicationReady() {
		time.Sleep(100 * time.Millisecond)
	}
	fmt.Println("Proceed to stop replication waiting for replication catch up")
	for result, err := s.checkReplicationCatchUp(); err != nil || !result; result, err = s.checkReplicationCatchUp() {
		time.Sleep(100 * time.Millisecond)
		fmt.Println("Waiting for replication catch up")
	}
	fmt.Println("Replication catch up, start to drop subscription")
	timestamp := time.Now().UnixNano() / int64(time.Millisecond)
	s.rdb.Cache.Set(context.Background(), "stop-replication-timestamp", timestamp, 0)
	err := s.dropDestSubscription()

	return timestamp, err
}
