package services

import (
	"context"
	"encoding/json"
	"fmt"
	"strconv"

	"github.com/go-redis/redis/v8"
	"github.com/rweebs/cdc-bowo/internal/app/config"
	"github.com/rweebs/cdc-bowo/internal/app/lib"
	"github.com/rweebs/cdc-bowo/internal/app/model"
	"github.com/rweebs/cdc-bowo/internal/app/utils"
)

type CDCSourceServices struct {
	dbSource           lib.Database
	dbDest             lib.Database
	rdb                lib.Cache
	primaryKeyList     map[string][]string
	RedisStreamList    map[string]string
	transformationList map[string]config.DDLTransform
	config             config.Config
}

func (s *CDCSourceServices) ExecuteDDLChange() {
	fmt.Println(s.config.SQLScript)
}
func (s *CDCSourceServices) StartService() {
	mainContext := context.Background()
	// Loop:
	for {
		var ctx context.Context
		// val, _ := s.getTimeStampCutOff()
		// if val > 0 {
		// ctx, _ = context.WithTimeout(mainContext, 3*time.Second)
		// defer cancel()
		// } else {
		ctx = mainContext
		// }
		// fmt.Println(ctx)
		entries, err := s.rdb.Cache.XRead(ctx, &redis.XReadArgs{

			Streams: makeStream(s.RedisStreamList),
			Count:   1,
			Block:   0,
		}).Result()
		if err != nil {
			fmt.Println(err)
			// continue
		}
		// if len(entries) == 0 {
		// 	break Loop
		// }
		for _, streamEntries := range entries {
			for _, entry := range streamEntries.Messages {

				fmt.Println("Received event from stream", streamEntries.Stream)
				for _, v := range entry.Values {
					// fmt.Println(v)
					var sql string
					var dat model.AutoGenerated
					if err := json.Unmarshal([]byte(fmt.Sprintf("%v", v)), &dat); err != nil {
						continue
					}
					// if timeCutOff, err := s.getTimeStampCutOff(); err == nil && dat.Payload.TsMs > timeCutOff {
					// 	break Loop
					// }
					// data, _ := json.MarshalIndent(dat, "", "  ")
					// // Print json formatted
					// // fmt.Println(key)
					// fmt.Println(string(data))
					// fmt.Println(val)
					if val, ok := s.transformationList[fmt.Sprintf("%s.%s", dat.Payload.Source.Schema, dat.Payload.Source.Table)]; ok {
						dat = utils.ConvertSchema(dat, val)

						sql = utils.ConvertDataToSQL(dat, s.primaryKeyList, val)
					} else {
						sql = utils.ConvertDataToSQL(dat, s.primaryKeyList, config.DDLTransform{})
					}
					result, err := utils.SQLExecutor(s.dbSource.Db, sql)
					fmt.Println(result, err)
				}
				s.RedisStreamList[streamEntries.Stream] = entry.ID
			}
		}
	}
}

func (s *CDCSourceServices) StopService() {
	data, _ := json.Marshal(s.RedisStreamList)
	s.rdb.Cache.Set(context.Background(), "sourceRedisStreamList", data, 0)
	fmt.Println("Stop Source Service")
}

func (s *CDCSourceServices) getTimeStampCutOff() (int64, error) {
	res, err := s.rdb.Cache.Get(context.Background(), "cdc-source-expired").Result()
	if err != nil {
		return 0, err
	}
	result, err := strconv.ParseInt(res, 10, 64)
	return result, err
}

func NewCDCSourceServices(dbSource lib.Database, dbDest lib.Database, rdb lib.Cache, config config.Config) *CDCSourceServices {
	return &CDCSourceServices{
		dbSource:           dbSource,
		dbDest:             dbDest,
		rdb:                rdb,
		primaryKeyList:     initPrimaryKeyList(dbSource.Db),
		RedisStreamList:    initRedisStreamList(dbSource.Db, rdb.Cache, "sourceRedisStreamList"),
		config:             config,
		transformationList: initTransformList(config.DDLTransform),
	}
}

func initTransformList(configs config.DDLTransform) map[string]config.DDLTransform {
	transformList := map[string]config.DDLTransform{}
	//TODO:
	for _, v := range configs.AddColumn {
		schemaTable := fmt.Sprintf("%s.%s", v.Schema, v.Table)
		object := transformList[schemaTable]
		object.AddColumn = append(object.AddColumn, v)
		transformList[schemaTable] = object
	}
	//DONE:
	for _, v := range configs.DropColumn {
		schemaTable := fmt.Sprintf("%s.%s", v.Schema, v.Table)
		object := transformList[schemaTable]
		object.DropColumn = append(object.DropColumn, v)
		transformList[schemaTable] = object
	}
	//TODO:
	for _, v := range configs.DropNotNullConstraint {
		schemaTable := fmt.Sprintf("%s.%s", v.Schema, v.Table)
		object := transformList[schemaTable]
		object.DropNotNullConstraint = append(object.DropNotNullConstraint, v)
		transformList[schemaTable] = object
	}
	//TODO:
	for _, v := range configs.ModifyDataType {
		schemaTable := fmt.Sprintf("%s.%s", v.Schema, v.Table)
		object := transformList[schemaTable]
		object.ModifyDataType = append(object.ModifyDataType, v)
		transformList[schemaTable] = object
	}
	//DONE:
	for _, v := range configs.RenameColumn {
		schemaTable := fmt.Sprintf("%s.%s", v.Schema, v.Table)
		object := transformList[schemaTable]
		object.RenameColumn = append(object.RenameColumn, v)
		transformList[schemaTable] = object
	}
	//DONE:
	for _, v := range configs.RenameTable {
		schemaTable := fmt.Sprintf("%s.%s", v.Schema, v.OldName)
		object := transformList[schemaTable]
		object.RenameTable = append(object.RenameTable, v)
		transformList[schemaTable] = object
	}

	return transformList
}
