version: '3.9'
services:
  postgresdb:
    image: debezium/postgres:13-alpine
    container_name: postgres1
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=helper
      - DATABASE_HOST=postgresdb
    ports:
      - '5434:5432'
    networks:
      - learning

  postgresdb2:
    image: debezium/postgres:13-alpine
    container_name: postgres2
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=helper
      - DATABASE_HOST=postgresdb
    ports:
      - '5433:5432'
    networks:
      - learning

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '36379:6379'
    command: redis-server
    volumes: 
      - cache:/data
    networks:
      - learning

  app:
    container_name: cdc
    image: rweebs/cdc:1.0.4
    platform: linux/x86_64
    tty: true
    build: .
    restart: on-failure
    volumes:
      - ./config:/config
    depends_on:
      - postgresdb
      - postgresdb2
      - cache
    networks:
      - learning
volumes:
  db-data:
  db-data-2:
  cache:
  
## Networks to be created to facilitate communication between containers
networks:
  learning:
    driver: bridge