package model

type Debeziumtemp struct {
	Stream   string `json:"Stream"`
	Messages []struct {
		ID     string        `json:"ID"`
		Values AutoGenerated `json:"Values"`
	} `json:"Messages"`
}
type AutoGenerated struct {
	Schema  Schema  `json:"schema"`
	Payload Payload `json:"payload"`
}
type Fields2 struct {
	Type     string      `json:"type"`
	Optional bool        `json:"optional"`
	Default  interface{} `json:"default,omitempty"`
	Name     string      `json:"name,omitempty"`
	Field    string      `json:"field"`
}
type Fields struct {
	Type     string    `json:"type"`
	Fields   []Fields2 `json:"fields,omitempty"`
	Optional bool      `json:"optional"`
	Name     string    `json:"name,omitempty"`
	Field    string    `json:"field"`
	Version  int       `json:"version,omitempty"`
}
type Schema struct {
	Type     string   `json:"type"`
	Fields   []Fields `json:"fields"`
	Optional bool     `json:"optional"`
	Name     string   `json:"name"`
	Version  int      `json:"version"`
}

type Source struct {
	Version   string      `json:"version"`
	Connector string      `json:"connector"`
	Name      string      `json:"name"`
	TsMs      int64       `json:"ts_ms"`
	Snapshot  string      `json:"snapshot"`
	Db        string      `json:"db"`
	Sequence  string      `json:"sequence"`
	Schema    string      `json:"schema"`
	Table     string      `json:"table"`
	TxID      int         `json:"txId"`
	Lsn       int         `json:"lsn"`
	Xmin      interface{} `json:"xmin"`
}
type Payload struct {
	Before      interface{} `json:"before"`
	After       interface{} `json:"after"`
	Source      Source      `json:"source"`
	Op          string      `json:"op"`
	TsMs        int64       `json:"ts_ms"`
	Transaction interface{} `json:"transaction"`
}

type PrimaryKey struct {
	Schema string
	Table  string
	Column []string
}
